### ISSUE TITLE
MySQL/MariaDB - ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by angelmanst** [bpatrik/pigallery2#100]
Hi,

When I try to configure pigallery to use the MySQL instance on my raspberry I get:
Error: Error while saving database settings: QueryFailedError: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes

When I check the output of the process I get:
9/9/2019, 3:17:28 PM[[32mINFO[39m] Updating database scheme
9/9/2019, 3:17:28 PM[[33mWARN[39m] Handled error:
ErrorDTO {
  code: 13,
  message: 'Error while saving database settings: QueryFailedError: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes',
  details: 
   { QueryFailedError: ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes
       at QueryFailedError.Error (native)
       at new QueryFailedError (/var/www/pigallery/node_modules/typeorm/error/QueryFailedError.js:11:28)
       at Query.<anonymous> (/var/www/pigallery/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:169:45)
       at Query.<anonymous> (/var/www/pigallery/node_modules/mysql/lib/Connection.js:525:10)
       at Query._callback (/var/www/pigallery/node_modules/mysql/lib/Connection.js:491:16)
       at Query.Sequence.end (/var/www/pigallery/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
       at Query.ErrorPacket (/var/www/pigallery/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
       at Protocol._parsePacket (/var/www/pigallery/node_modules/mysql/lib/protocol/Protocol.js:291:23)
       at Parser._parsePacket (/var/www/pigallery/node_modules/mysql/lib/protocol/Parser.js:433:10)
       at Parser.write (/var/www/pigallery/node_modules/mysql/lib/protocol/Parser.js:43:10)
     message: 'ER_TOO_LONG_KEY: Specified key was too long; max key length is 767 bytes',
     code: 'ER_TOO_LONG_KEY',
     errno: 1071,
     sqlMessage: 'Specified key was too long; max key length is 767 bytes',
     sqlState: '42000',
     index: 0,
     sql: 'CREATE TABLE `user_entity` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `role` smallint NOT NULL, `permissions` text NULL, UNIQUE INDEX `IDX_3fe76ecf0f0ef036ff981e9f67` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB',
     name: 'QueryFailedError',
     query: 'CREATE TABLE `user_entity` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `password` varchar(255) NOT NULL, `role` smallint NOT NULL, `permissions` text NULL, UNIQUE INDEX `IDX_3fe76ecf0f0ef036ff981e9f67` (`name`), PRIMARY KEY (`id`)) ENGINE=InnoDB',
     parameters: [] } }

I'm using:
raspberry: Pi 3 Model B
OS: Linux 4.14.78-4-osmc
mysql  Ver 15.1 Distrib 10.1.38-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2
npm -version: 6.11.3

Any additional information you might need to pinpoint the issue just let me know.

Is there a way to create the database schema for the pigallery?

Regards,
Marco

**Comment by bpatrik** [comment]
Hi,

Can you tell which pigallery version are you using?

Best,
Patrik

**Comment by angelmanst** [comment]
Hi Patrik,

I've installed Version 1.7.0

I had a few issues upgrading to this version. But I think I was finally able to put it to work. The issue is that I can't seam to put the database to work (either SQLite or MySQL).
I've open this issue for the MySQL because the SQLite issue is more related to install SQLite with npm.

Regards,
Marco

**Comment by bpatrik** [comment]
Hi,

Thank is interesting. There was a related issue earlier:  #79 , but I could not reproduce and fix that time.

Can you maybe try to creat the mysql db from scratch? 
I'm using: UTF 8 Unicode char set. with utf8_general_ci collocation. (I don't think that it has anylting to do with the too long key tho) with MySQL 5.7.14 on Win.

Also what is your issue with sqlite? That should be straight forward.
Also what is you node version? I'm using `node v10.15.0` on `Raspbian GNU/Linux 9 (stretch)` with an RPI 3. 

Best,
Patrik

**Comment by angelmanst** [comment]
Hi Patrick,

I was able to overcome this issue (creating the schema) by dropping the database and recreating it with utf8.

Steps taken:
1 - Signin to MySQL
- sudo -s
- mysql

2 - Drop database
- drop database pigallery;

3 - Recreate database from scratch with utf8
- CREATE DATABASE pigallery CHARACTER SET utf8;

After this, I login to pigallery online and changed the configuration to use this database.
Pigallery created the tables (and I'm guessing, everything it needs).

I had to do several restarts to the application and edit the config.json file with the correct MySQL configuration because it kept defaulting back to SQLite and memory database.
But eventually it got the MySQL as primary database and is using it now.

It seams that the issue was trying to reuse a database that was already used by a previous version of pigallery.

Thanks for the tip of recreating the database.

As for the SQLite issue I'll try to open a new issue with a proper description.

Regards,
Marco
