### ISSUE TITLE
Create the thumbnail folder (recursively?) if it does not exist yet

### ISSUE THREAD

**Issue by contradictioned** [bpatrik/pigallery2#106]
**Is your feature request related to a problem? Please describe.**
I installed pigallery2 and tried it for the first time. I did not change any settings, so the thumbnail folder is set to `demo/TEMP`. When I tried to index with thumbnails, or also browse a folder with images, the following error occurs:

```
nhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir '/srv/pigallery2/demo/TEMP'
    at Object.mkdirSync (fs.js:757:3)
    at Function.<anonymous> (/srv/pigallery2/backend/middlewares/thumbnail/ThumbnailGeneratorMWs.js:254:32)
    at step (/srv/pigallery2/backend/middlewares/thumbnail/ThumbnailGeneratorMWs.js:32:23)
    at Object.next (/srv/pigallery2/backend/middlewares/thumbnail/ThumbnailGeneratorMWs.js:13:53)
    at /srv/pigallery2/backend/middlewares/thumbnail/ThumbnailGeneratorMWs.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/srv/pigallery2/backend/middlewares/thumbnail/ThumbnailGeneratorMWs.js:3:12)
    at Function.ThumbnailGeneratorMWs.generateImage (/srv/pigallery2/backend/middlewares/thumbnail/ThumbnailGeneratorMWs.js:241:16)
    at /srv/pigallery2/backend/middlewares/thumbnail/ThumbnailGeneratorMWs.js:189:35
    at Layer.handle [as handle_request] (/srv/pigallery2/node_modules/express/lib/router/layer.js:95:5)
(node:29168) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29168) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Describe the solution you'd like**
I guess, without reading code, that pigallery2 tries to create the folder without making sure the parents exist. So we should be calling `mkdir -p` or something similar that makes sure, parent directories exist.
As I was running pigallery2 as root, there was no problem with permissions.

**Comment by bpatrik** [comment]
thanks, I'll look into it.

Best,
Patrik

**Comment by bpatrik** [comment]
Hi,

I decided to leave it like as it is, I find it more foolproof.
(assuming you do not handle users on linux properly and ) accidentally setting a wrong path, you will get an error instead of creating  several folders.

Best,
Patrik
