### ISSUE TITLE
EBADCSRFTOKEN

### ISSUE THREAD

**Issue by Suika** [bpatrik/pigallery2#118]
**Describe the bug**
After the last upgrade, applictaion fails to login due to an invalid csrf token.

```
1/3/2020, 12:32:19 AM[ERROR] Unexpected error:
ForbiddenError: invalid csrf token
    at csrf (/app/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/app/node_modules/cookie-parser/index.js:71:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7 {
  message: 'invalid csrf token',
  code: 'EBADCSRFTOKEN'
}
1/3/2020, 12:32:19 AM[WARN] Handled error:
ErrorDTO {
  code: 10,
  message: 'Unknown server side error',
  details: ForbiddenError: invalid csrf token
      at csrf (/app/node_modules/csurf/index.js:112:19)
      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
      at /app/node_modules/express/lib/router/index.js:284:7
      at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
      at next (/app/node_modules/express/lib/router/index.js:275:10)
      at cookieParser (/app/node_modules/cookie-parser/index.js:71:5)
      at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
      at /app/node_modules/express/lib/router/index.js:284:7 {
    message: 'invalid csrf token',
    code: 'EBADCSRFTOKEN'
  },
  detailsStr: 'ForbiddenError: invalid csrf token'
}
```

**Environment (please complete the following information):**
 - bpatrik/pigallery2:nightly-stretch sha256:4ade234a8f5f37a7eeb5104649a1fb9c83247faccc14e9c5a2a918a069a6db6a

**Used app version**:
- docker-nightly

**Comment by bpatrik** [comment]
Hi,

Thanks for the report. 
I have temporarly reverted csrf support. It should work now (after the build is done).

PS: I was able to properly build and run (on RPI3) the alpine version too. tag: `nightly-alpine`.

**Comment by bpatrik** [comment]
Hi this one should be fixed with this commit: https://github.com/bpatrik/pigallery2/commit/5b4f06e7899077d44084dd5d28551bbb9db04dfe
