### ISSUE TITLE
Settings Reset w/sqlite DB caused backup config.json file to not be useable

### ISSUE THREAD

**Issue by TechZerkerGit** [bpatrik/pigallery2#160]
**Describe the bug**

Setup PiGallery, with the sqlite database option, with everything working, authentication turned off, like on the demo site. In anticipation that this unauthenticated site would leave the settings screen available for others to modify, made a backup of my production *config.json* file.

Following day, someone did go into settings, and reset one of the file paths, so that the site was not working correctly. Removed the *config.json* and copied my backup config.json with all my settings back in place. When the app is restarted, it failed to start, looking for the *demo* paths. Checking the *config.json*, and it's a fully default/new install config for all settings.

Tried a second time, made sure application was stopped, replaced config.json with my backup copy, and started app, with same issue. Re-checked config.json, and it does not match my backup, it's a fully new install config.

I expect what is happening, with my limited knowledge on this app, and feel free to give direction to gather some logs. Is whatever other settings were changed, changes were saved into the sqlite database, and because my backup config.json file now has some setting mis-match with what sqlite is expecting, it reverts/re-writes a new config.json.

The work-around for now that seems to be working, is using the basic 'memory' type database with it's limited features. In memory type db, I changed some settings and saved them, stopped the server, restored my backup config.json file, and restarted, and the site loaded based on that config backup file without any issues.

NPM Log file below, from attempting to start after restoring my config.json file, the console itself after NPM Start only shows an error line for not finding the 'demo' paths, but that's because by that stage, it's trying to start from a default/new-install config, not sure if the log below shows anything that preempts that to show the config.json file being reset:

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pigallery2@1.8.0~prestart: pigallery2@1.8.0
6 info lifecycle pigallery2@1.8.0~start: pigallery2@1.8.0
7 verbose lifecycle pigallery2@1.8.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle pigallery2@1.8.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/techzerker/pigallery/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/home/techzerker/w$
9 verbose lifecycle pigallery2@1.8.0~start: CWD: /home/techzerker/pigallery
10 silly lifecycle pigallery2@1.8.0~start: Args: [ '-c', 'node ./src/backend/index.js' ]
11 silly lifecycle pigallery2@1.8.0~start: Returned: code: 1  signal: null
12 info lifecycle pigallery2@1.8.0~start: Failed to exec start script
13 verbose stack Error: pigallery2@1.8.0 start: `node ./src/backend/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid pigallery2@1.8.0
15 verbose cwd /home/techzerker/pigallery
16 verbose Linux 4.15.0-101-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.20.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error pigallery2@1.8.0 start: `node ./src/backend/index.js`
22 error Exit status 1
23 error Failed at the pigallery2@1.8.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
````

Second .npm log, if it helps, is from when I then tried starting 'npm start -- --config-path=<path to my backup config>

````
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--config-path',
1 verbose cli   '/home/techzerker/pigallery/config.json.backup' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pigallery2@1.8.0~prestart: pigallery2@1.8.0
6 info lifecycle pigallery2@1.8.0~start: pigallery2@1.8.0
7 verbose lifecycle pigallery2@1.8.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle pigallery2@1.8.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/techzerker/pigallery/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin:/home/techzerker/w$
9 verbose lifecycle pigallery2@1.8.0~start: CWD: /home/techzerker/pigallery
10 silly lifecycle pigallery2@1.8.0~start: Args: [ '-c',
10 silly lifecycle   'node ./src/backend/index.js "--config-path" "/home/techzerker/pigallery/config.json.backup"' ]
11 silly lifecycle pigallery2@1.8.0~start: Returned: code: 1  signal: null
12 info lifecycle pigallery2@1.8.0~start: Failed to exec start script
13 verbose stack Error: pigallery2@1.8.0 start: `node ./src/backend/index.js "--config-path" "/home/techzerker/pigallery/config.json.backup"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid pigallery2@1.8.0
15 verbose cwd /home/techzerker/pigallery
16 verbose Linux 4.15.0-101-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "--" "--config-path" "/home/techzerker/pigallery/config.json.backup"
18 verbose node v10.20.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error pigallery2@1.8.0 start: `node ./src/backend/index.js "--config-path" "/home/techzerker/pigallery/config.json.backup"`
22 error Exit status 1
23 error Failed at the pigallery2@1.8.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
````

The only settings changed in the config file were Authentication/Password turned off, the Server Port changed, and then the two file paths.

**Environment (please complete the following information):**
 - OS: VPS on Ubuntu 18.04

**Used app version**:
- Release Binary, Manual Install - Current 1.8.0 release (installed 2020-05-30)

**Comment by bpatrik** [comment]
Hi,

Copying back your backup config should actually work.
I do not store any settings in db, only in the config.json.
The config file is overwritten every now and then (like at start up or when you change the settings).

I'm not sure what could have gone wrong, but I suggest to try creating your sqite version.

You can also change the default user to be a 'simple' user and not an admin, so others cannot change the settings. (its only possible if you directly edit the config.josn, is should be called something like `unAuthenticatedUserRole`)

Hope it helps!

Patrik

**Comment by TechZerkerGit** [comment]
Thanks for the direct response Patrik, greatly appreciated!

I'll give the simple user mode a try from the config file, to lock out the settings from the web interface, and then mess some more with the config file.
I setup a basic Systemd service that was starting up the node run of PiGallery, and that seemed to have the highest impact on the config file being reset to defaults.

I'll try those settings and moving back to sqlite, and see if the issue comes back, and let you know how it goes :)
When I get a chance, I'll do a little write up on the project to post up on my corner of the web (https://techzerker.com), because it's exactly what I was looking for, every other gallery app I could find wanted to store critical information in a database or re-organize the files, vs. just looking at my flat file structure and running with it :)

I'm not in the position right now to do much for donating to projects, but I'm keeping a tally so that when I can, I can come back around and pitch in :)

Thanks!
--Scott

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by TechZerkerGit** [comment]
Good Evening!

Update: That worked much better! I think whatever was happening before with SQLite was just being triggered by someone else mucking with settings, or plain old hitting settings and selecting "Reset" on some of them :P

In Config.json, it was "unAuthenticatedUserRole" for the setting, except it was numeric, so reducing it from "4" to "1" fully hid access to the settings menu from the web interface, so it can't be messed with :P

Thanks!
--Scott

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bpatrik** [comment]
closing due to inactivity
