### ISSUE TITLE
Having trouble starting PiGallery2 on Ubuntu 20.04 LTS - missing folders during install?

### ISSUE THREAD

**Issue by EricLauber** [bpatrik/pigallery2#166]
**Describe the bug**
Although Docker is the supported and recommended method of install, I am attempting to follow the **1.2** install path on a new Ubuntu 20.04 server. Installation works fine, but then attempting `npm start` fails. Similar failures occur when following up with the file-permissions recommendation and starting with a different port.

I've included console and log output below. However, I did create `/demo/tmp` and `/demo/images` myself, and was then able to `npm start`. Maybe this should be a specific instruction to change in the `config.json` before starting?

**Console Feedback**
```
MYUSER@MYHOSTNAME:~/pigallery2$ npm start

> pigallery2@1.8.0 start /home/MYUSER/pigallery2
> node ./src/backend/index.js

internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir '/home/MYUSER/pigallery2/demo/tmp'
    at Object.mkdirSync (fs.js:914:3)
    at ProjectPathClass.reset (/home/MYUSER/pigallery2/src/backend/ProjectPath.js:28:16)
    at new ProjectPathClass (/home/MYUSER/pigallery2/src/backend/ProjectPath.js:8:14)
    at Object.<anonymous> (/home/MYUSER/pigallery2/src/backend/ProjectPath.js:32:23)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: '/home/MYUSER/pigallery2/demo/tmp'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pigallery2@1.8.0 start: `node ./src/backend/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pigallery2@1.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/MYUSER/.npm/_logs/2020-07-04T19_39_06_107Z-debug.log
```

Here is then the output from the referenced debug log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pigallery2@1.8.0~prestart: pigallery2@1.8.0
6 info lifecycle pigallery2@1.8.0~start: pigallery2@1.8.0
7 verbose lifecycle pigallery2@1.8.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle pigallery2@1.8.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/MYUSER/pigallery2/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle pigallery2@1.8.0~start: CWD: /home/MYUSER/pigallery2
10 silly lifecycle pigallery2@1.8.0~start: Args: [ '-c', 'node ./src/backend/index.js' ]
11 silly lifecycle pigallery2@1.8.0~start: Returned: code: 1  signal: null
12 info lifecycle pigallery2@1.8.0~start: Failed to exec start script
13 verbose stack Error: pigallery2@1.8.0 start: `node ./src/backend/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid pigallery2@1.8.0
15 verbose cwd /home/MYUSER/pigallery2
16 verbose Linux 5.4.0-40-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error pigallery2@1.8.0 start: `node ./src/backend/index.js`
22 error Exit status 1
23 error Failed at the pigallery2@1.8.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 LTS

**Used app version**:
- The current release

**Comment by bpatrik** [comment]
Hi,

The issue seems to be this line 
```Error: ENOENT: no such file or directory, mkdir '/home/MYUSER/pigallery2/demo/tmp'```
It is called here: https://github.com/bpatrik/pigallery2/blob/3deb8e26f5cda166d32c34188d12583ab00f6272/src/backend/ProjectPath.ts#L38-L39

The app tries to create the tmp folder if not exist. There can be two issues with your setup:
1) it exist somewhere else and the given path is not writable
2) the folder exists right there, but the app does not have read/write rights on it.

I hope it helps!

**Comment by gitbs** [comment]
I hit the same problem. 
Tried to resolve by simply creating the pigallery2/demo/tmp manually, then it snowballs into other issues (running as root):
`
> pigallery2@1.8.0 start /root/pigallery2/pigallery2
> node ./src/backend/index.js

8/9/2020, 6:36:21 PM[INFO] [server] Running in DEBUG mode, set env variable NODE_ENV=production to disable 
8/9/2020, 6:36:21 PM[INFO] [server] running diagnostics...
(node:220488) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
8/9/2020, 6:36:21 PM[WARN] [ConfigDiagnostics] [SQL error] DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
8/9/2020, 6:36:21 PM[WARN] [ConfigDiagnostics] Error during initializing SQL falling back temporally to memory DB
8/9/2020, 6:36:22 PM[WARN] [ConfigDiagnostics] Video support error, switching off.. Error: Error accessing ffmpeg, cant find executable: Error: Cannot find ffmpeg
8/9/2020, 6:36:22 PM[ERROR] [ConfigDiagnostics] Images folder error Images folder not exists: 'demo/images'
8/9/2020, 6:36:22 PM[WARN] [ConfigDiagnostics] Faces are not supported with these settings, switching off.. Error: Memory Database do not support faces
Error: ENOENT: no such file or directory, open '/root/pigallery2/pigallery2/db/users.db'
    at Object.openSync (fs.js:465:3)
    at Object.writeFileSync (fs.js:1416:35)
    at UserManager.saveDB (/root/pigallery2/pigallery2/src/backend/model/database/memory/UserManager.js:103:12)
    at new UserManager (/root/pigallery2/pigallery2/src/backend/model/database/memory/UserManager.js:33:14)
    at Function.<anonymous> (/root/pigallery2/pigallery2/src/backend/model/ObjectManagers.js:94:56)
    at Generator.next (<anonymous>)
    at fulfilled (/root/pigallery2/pigallery2/src/backend/model/ObjectManagers.js:4:58) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/root/pigallery2/pigallery2/db/users.db'
}
(node:220488) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/root/pigallery2/pigallery2/db/users.db'
    at Object.openSync (fs.js:465:3)
    at Object.writeFileSync (fs.js:1416:35)
    at UserManager.saveDB (/root/pigallery2/pigallery2/src/backend/model/database/memory/UserManager.js:103:12)
    at UserManager.<anonymous> (/root/pigallery2/pigallery2/src/backend/model/database/memory/UserManager.js:67:18)
    at Generator.next (<anonymous>)
    at /root/pigallery2/pigallery2/src/backend/model/database/memory/UserManager.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/pigallery2/pigallery2/src/backend/model/database/memory/UserManager.js:3:12)
    at UserManager.createUser (/root/pigallery2/pigallery2/src/backend/model/database/memory/UserManager.js:63:16)
    at new UserManager (/root/pigallery2/pigallery2/src/backend/model/database/memory/UserManager.js:31:18)
(node:220488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:220488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:220500) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
`

reproed both on x86/nodejs 12.18.3 and aarch64/nodejs 14.7

Note: in docker it runs just fine.

**Comment by bpatrik** [comment]
@gitbs my first guess would be that the app cannot write the '/root/pigallery2/pigallery2/db/' folder.
users.db is actually a text file where I persist the users with the memory db.

But the root cause of the problem is this: "try to install it: npm install sqlite3 --save". Most likely you do not have that package as it is an optional dependency.


ps: I really recommend using docker. I'm also using it on my rp3 since 2019, without an issue. My life have changed recently and I have way less time to answer these questions (like every 3 months 1-2 days)

**Comment by bpatrik** [comment]
closing due to inactivity
