### ISSUE TITLE
Unable to read data from mounted NFS share

### ISSUE THREAD

**Issue by EricLauber** [bpatrik/pigallery2#167]
**Describe the bug**
I lack Linux experience so maybe this isn't an issue with PiGallery2.

I have a QNAP NAS. I have read-only shares available on the NAS and these are available via NFS, which is QNAP's recommended path to mounting shares in Linux. I have mounted the shares manually such as with `sudo mount NASIP:/share local/folder` and have also used (and currently have configured) `etc/fstab`. Both of these appear to work fine from the terminal. I can browse to the share, see files, copy them out, etc.

When I mount one of these shares as a subdirectory within the configured PiGallery2 folder, I get errors. On the web application, the album for that folder shows up as a link, but appears to load forever. I also get some errors in my terminal.

```
7/5/2020, 6:09:51 PM[WARN] Handled error:
ErrorDTO {
  code: 7,
  message: 'no such file:LOCALLYMAPPEDFOLDER/MYIMAGE.jpg',
  details: "can't find file: /home/MYUSER/pigallery2/demo/images/LOCALLYMAPPEDFOLDER/MYIMAGE.jpg",
  detailsStr: "can't find file: /home/MYUSER/pigallery2/demo/images/LOCALLYMAPPEDFOLDER/MYIMAGE.jpg"
}
```

And
```
(node:30997) UnhandledPromiseRejectionWarning: Error: UNKNOWN: unknown error, stat '/home/MYUSER/pigallery2/demo/images/LOCALLYMAPPEDFOLDER'
    at Object.statSync (fs.js:1009:3)
    at /home/MYUSER/pigallery2/src/backend/middlewares/GalleryMWs.js:31:21
    at Generator.next (<anonymous>)
    at /home/MYUSER/pigallery2/src/backend/middlewares/GalleryMWs.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/MYUSER/pigallery2/src/backend/middlewares/GalleryMWs.js:3:12)
    at listDirectory (/home/MYUSER/pigallery2/src/backend/middlewares/GalleryMWs.js:27:16)
    at Layer.handle [as handle_request] (/home/MYUSER/pigallery2/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/MYUSER/pigallery2/node_modules/express/lib/router/route.js:137:13)
    at /home/MYUSER/pigallery2/src/backend/middlewares/VersionMWs.js:26:17
(node:30997) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 Server LTS

**Used app version**:
- the latest release

**Comment by bpatrik** [comment]
I'm not totally sure what could be an issue here.

Can you double check if the app has read rights on the files? Not only read (list) right on the folder?
It seems that that app can list the folder and files in them, otherwise it would not know about `/home/MYUSER/pigallery2/demo/images/LOCALLYMAPPEDFOLDER/MYIMAGE.jpg`

I know that there is an issue if there is some special characters in the path. Generally it should work, but I can recall starting a file/folder with `.` may cause issues.

I would try 2 things:

1) copy some of the photos to a local folder, set the galley images folder to that local folder. This way you can be sure that it works and you have some issue with your path setup
2) give [chmod 777](https://www.howtogeek.com/437958/how-to-use-the-chmod-command-on-linux/) to a few of photos and all directories in the path. This way you can make sure that rights were not the issue (do not forget to undo it afterwards :) )

**Comment by bpatrik** [comment]
Closing this due to inactivity
