### ISSUE TITLE
User roles described in USERRIGHTS.md does not exist

### ISSUE THREAD

**Issue by twatzl** [bpatrik/pigallery2#173]
Hi, I am trying to setup pigallery as a public gallery on my server. 

**Expected Behaviour**

What I would like to achieve is that a not logged in user can see all images and media, but cannot change settings.
According to https://github.com/bpatrik/pigallery2/blob/master/USERRIGHTS.md this should be the case for the role "Guest".

**Actual Behaviour**

I have set the default user role according to the roles listed in 
https://github.com/bpatrik/pigallery2/blob/master/USERRIGHTS.md
to "Guest", but it seems this does not work.

relevant parts of my docker-compose.yml:
```
services:
  pigallery2:
    image: bpatrik/pigallery2:latest
    environment:
      - NODE_ENV=production
      - Server-Database-type=mysql
      - Server-Database-mysql-host=db
      - Server-Database-mysql-port=3306
      - Server-Database-mysql-database=pigallery2
      - Server-Database-mysql-username=someuser # TODO: change
      - Server-Database-mysql-password=somepass # TODO: change
      - Client-unAuthenticatedUserRole=Guest
```

I am starting with a clean Database and clean directories.

Stacktrace:
```
pigallery2_1  | /app/src/common/config/private/ConfigClass.js:46
pigallery2_1  |             throw new Error('Unknown user role for Client.unAuthenticatedUserRole, found: ' + this.Client.unAuthenticatedUserRole);
pigallery2_1  |             ^
pigallery2_1  | 
pigallery2_1  | Error: Unknown user role for Client.unAuthenticatedUserRole, found: Guest
pigallery2_1  |     at ConfigClass.load (/app/src/common/config/private/ConfigClass.js:46:19)
pigallery2_1  |     at Object.<anonymous> (/app/src/common/config/private/Config.js:5:16)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
pigallery2_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
pigallery2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
pigallery2_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
pigallery2_1  |     at require (internal/modules/cjs/helpers.js:74:18)
pigallery2_1  |     at Object.<anonymous> (/app/src/backend/model/database/sql/enitites/EntityUtils.js:3:18)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  | using config path:/app/data/config/config.json
pigallery2_1  | /app/src/common/config/private/ConfigClass.js:46
pigallery2_1  |             throw new Error('Unknown user role for Client.unAuthenticatedUserRole, found: ' + this.Client.unAuthenticatedUserRole);
pigallery2_1  |             ^
pigallery2_1  | 
pigallery2_1  | Error: Unknown user role for Client.unAuthenticatedUserRole, found: Guest
pigallery2_1  |     at ConfigClass.load (/app/src/common/config/private/ConfigClass.js:46:19)
pigallery2_1  |     at Object.<anonymous> (/app/src/common/config/private/Config.js:5:16)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
pigallery2_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
pigallery2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
pigallery2_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
pigallery2_1  |     at require (internal/modules/cjs/helpers.js:74:18)
pigallery2_1  |     at Object.<anonymous> (/app/src/backend/model/database/sql/enitites/EntityUtils.js:3:18)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  | using config path:/app/data/config/config.json
pigallery2_1  | /app/src/common/config/private/ConfigClass.js:46
pigallery2_1  |             throw new Error('Unknown user role for Client.unAuthenticatedUserRole, found: ' + this.Client.unAuthenticatedUserRole);
pigallery2_1  |             ^
pigallery2_1  | 
pigallery2_1  | Error: Unknown user role for Client.unAuthenticatedUserRole, found: Guest
pigallery2_1  |     at ConfigClass.load (/app/src/common/config/private/ConfigClass.js:46:19)
pigallery2_1  |     at Object.<anonymous> (/app/src/common/config/private/Config.js:5:16)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
pigallery2_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
pigallery2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
pigallery2_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
pigallery2_1  |     at require (internal/modules/cjs/helpers.js:74:18)
pigallery2_1  |     at Object.<anonymous> (/app/src/backend/model/database/sql/enitites/EntityUtils.js:3:18)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  | using config path:/app/data/config/config.json
pigallery2_1  | /app/src/common/config/private/ConfigClass.js:46
pigallery2_1  |             throw new Error('Unknown user role for Client.unAuthenticatedUserRole, found: ' + this.Client.unAuthenticatedUserRole);
pigallery2_1  |             ^
pigallery2_1  | 
pigallery2_1  | Error: Unknown user role for Client.unAuthenticatedUserRole, found: Guest
pigallery2_1  |     at ConfigClass.load (/app/src/common/config/private/ConfigClass.js:46:19)
pigallery2_1  |     at Object.<anonymous> (/app/src/common/config/private/Config.js:5:16)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
pigallery2_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
pigallery2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
pigallery2_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
pigallery2_1  |     at require (internal/modules/cjs/helpers.js:74:18)
pigallery2_1  |     at Object.<anonymous> (/app/src/backend/model/database/sql/enitites/EntityUtils.js:3:18)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  | using config path:/app/data/config/config.json
pigallery2_1  | /app/src/common/config/private/ConfigClass.js:46
pigallery2_1  |             throw new Error('Unknown user role for Client.unAuthenticatedUserRole, found: ' + this.Client.unAuthenticatedUserRole);
pigallery2_1  |             ^
pigallery2_1  | 
pigallery2_1  | Error: Unknown user role for Client.unAuthenticatedUserRole, found: Guest
pigallery2_1  |     at ConfigClass.load (/app/src/common/config/private/ConfigClass.js:46:19)
pigallery2_1  |     at Object.<anonymous> (/app/src/common/config/private/Config.js:5:16)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
pigallery2_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
pigallery2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
pigallery2_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
pigallery2_1  |     at require (internal/modules/cjs/helpers.js:74:18)
pigallery2_1  |     at Object.<anonymous> (/app/src/backend/model/database/sql/enitites/EntityUtils.js:3:18)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  | using config path:/app/data/config/config.json
pigallery2_1  | /app/src/common/config/private/ConfigClass.js:46
pigallery2_1  |             throw new Error('Unknown user role for Client.unAuthenticatedUserRole, found: ' + this.Client.unAuthenticatedUserRole);
pigallery2_1  |             ^
pigallery2_1  | 
pigallery2_1  | Error: Unknown user role for Client.unAuthenticatedUserRole, found: Guest
pigallery2_1  |     at ConfigClass.load (/app/src/common/config/private/ConfigClass.js:46:19)
pigallery2_1  |     at Object.<anonymous> (/app/src/common/config/private/Config.js:5:16)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
pigallery2_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
pigallery2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
pigallery2_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
pigallery2_1  |     at require (internal/modules/cjs/helpers.js:74:18)
pigallery2_1  |     at Object.<anonymous> (/app/src/backend/model/database/sql/enitites/EntityUtils.js:3:18)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  | using config path:/app/data/config/config.json
pigallery2_1  | /app/src/common/config/private/ConfigClass.js:46
pigallery2_1  |             throw new Error('Unknown user role for Client.unAuthenticatedUserRole, found: ' + this.Client.unAuthenticatedUserRole);
pigallery2_1  |             ^
pigallery2_1  | 
pigallery2_1  | Error: Unknown user role for Client.unAuthenticatedUserRole, found: Guest
pigallery2_1  |     at ConfigClass.load (/app/src/common/config/private/ConfigClass.js:46:19)
pigallery2_1  |     at Object.<anonymous> (/app/src/common/config/private/Config.js:5:16)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
pigallery2_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
pigallery2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
pigallery2_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
pigallery2_1  |     at require (internal/modules/cjs/helpers.js:74:18)
pigallery2_1  |     at Object.<anonymous> (/app/src/backend/model/database/sql/enitites/EntityUtils.js:3:18)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  | using config path:/app/data/config/config.json
pigallery2_1  | /app/src/common/config/private/ConfigClass.js:46
pigallery2_1  |             throw new Error('Unknown user role for Client.unAuthenticatedUserRole, found: ' + this.Client.unAuthenticatedUserRole);
pigallery2_1  |             ^
pigallery2_1  | 
pigallery2_1  | Error: Unknown user role for Client.unAuthenticatedUserRole, found: Guest
pigallery2_1  |     at ConfigClass.load (/app/src/common/config/private/ConfigClass.js:46:19)
pigallery2_1  |     at Object.<anonymous> (/app/src/common/config/private/Config.js:5:16)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
pigallery2_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
pigallery2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
pigallery2_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
pigallery2_1  |     at require (internal/modules/cjs/helpers.js:74:18)
pigallery2_1  |     at Object.<anonymous> (/app/src/backend/model/database/sql/enitites/EntityUtils.js:3:18)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  | using config path:/app/data/config/config.json
pigallery2_1  | /app/src/common/config/private/ConfigClass.js:46
pigallery2_1  |             throw new Error('Unknown user role for Client.unAuthenticatedUserRole, found: ' + this.Client.unAuthenticatedUserRole);
pigallery2_1  |             ^
pigallery2_1  | 
pigallery2_1  | Error: Unknown user role for Client.unAuthenticatedUserRole, found: Guest
pigallery2_1  |     at ConfigClass.load (/app/src/common/config/private/ConfigClass.js:46:19)
pigallery2_1  |     at Object.<anonymous> (/app/src/common/config/private/Config.js:5:16)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
pigallery2_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
pigallery2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
pigallery2_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
pigallery2_1  |     at require (internal/modules/cjs/helpers.js:74:18)
pigallery2_1  |     at Object.<anonymous> (/app/src/backend/model/database/sql/enitites/EntityUtils.js:3:18)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  | using config path:/app/data/config/config.json
pigallery2_1  | /app/src/common/config/private/ConfigClass.js:46
pigallery2_1  |             throw new Error('Unknown user role for Client.unAuthenticatedUserRole, found: ' + this.Client.unAuthenticatedUserRole);
pigallery2_1  |             ^
pigallery2_1  | 
pigallery2_1  | Error: Unknown user role for Client.unAuthenticatedUserRole, found: Guest
pigallery2_1  |     at ConfigClass.load (/app/src/common/config/private/ConfigClass.js:46:19)
pigallery2_1  |     at Object.<anonymous> (/app/src/common/config/private/Config.js:5:16)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
pigallery2_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
pigallery2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
pigallery2_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
pigallery2_1  |     at require (internal/modules/cjs/helpers.js:74:18)
pigallery2_1  |     at Object.<anonymous> (/app/src/backend/model/database/sql/enitites/EntityUtils.js:3:18)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  | using config path:/app/data/config/config.json
pigallery2_1  | /app/src/common/config/private/ConfigClass.js:46
pigallery2_1  |             throw new Error('Unknown user role for Client.unAuthenticatedUserRole, found: ' + this.Client.unAuthenticatedUserRole);
pigallery2_1  |             ^
pigallery2_1  | 
pigallery2_1  | Error: Unknown user role for Client.unAuthenticatedUserRole, found: Guest
pigallery2_1  |     at ConfigClass.load (/app/src/common/config/private/ConfigClass.js:46:19)
pigallery2_1  |     at Object.<anonymous> (/app/src/common/config/private/Config.js:5:16)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
pigallery2_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
pigallery2_1  |     at Module.load (internal/modules/cjs/loader.js:815:32)
pigallery2_1  |     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
pigallery2_1  |     at Module.require (internal/modules/cjs/loader.js:852:19)
pigallery2_1  |     at require (internal/modules/cjs/helpers.js:74:18)
pigallery2_1  |     at Object.<anonymous> (/app/src/backend/model/database/sql/enitites/EntityUtils.js:3:18)
pigallery2_1  |     at Module._compile (internal/modules/cjs/loader.js:959:30)
```

**Suggested Fix**

1. Init roles in database on startup so they match the documentation OR
2. Change/Improve the documentation about user roles

Best
Tobias

**Comment by twatzl** [comment]
So I found out that the real issue is that pigallery cannot connect to mariadb as described here https://github.com/bpatrik/pigallery2/issues/163 . I now reverted back to the default. 

However I still cannot figure out a way to make the gallery public without making the settings public.

**Comment by bpatrik** [comment]
Hi,
The issue is that user roles are defined by id not string. In februray I made a significant change on the config handling that enables also using strings to set config enums (i.e: use Guest here)

Also using Guest might be too restrictive, also Users already cannot change the settings.

**Comment by bpatrik** [comment]
Closing this due to inactivity
