### ISSUE TITLE
gallery.RANDOM stopped working.

### ISSUE THREAD

**Issue by Kadelam** [bpatrik/pigallery2#18]
```
(node:21718) UnhandledPromiseRejectionWarning: QueryFailedError: ER_SP_DOES_NOT_EXIST: FUNCTION gallery.RANDOM does not exist
    at new QueryFailedError (/home/kadelam/works/kmodules/pigallery2/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at Query.<anonymous> (/home/kadelam/works/kmodules/pigallery2/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:223:45)
    at Query.<anonymous> (/home/kadelam/works/kmodules/pigallery2/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/home/kadelam/works/kmodules/pigallery2/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/home/kadelam/works/kmodules/pigallery2/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/kadelam/works/kmodules/pigallery2/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/home/kadelam/works/kmodules/pigallery2/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/home/kadelam/works/kmodules/pigallery2/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/kadelam/works/kmodules/pigallery2/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/kadelam/works/kmodules/pigallery2/node_modules/mysql/lib/Connection.js:91:28)
(node:21718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21718) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Node version is 11.1.0

**Comment by bpatrik** [comment]
Hi,

Thank you for the report. I'll look in to this problem in the next few weeks. 
Officially the app does not support node 11, only  node ` >= 6.9 <11.0`. (But I think this is not the problem here.)
Until I fix this error, you may give a try to the `sqlite` base database. That is more tested.

**Comment by Kadelam** [comment]
Hi,

Just to confirm, random works with the sqlite backend.

**Comment by bpatrik** [comment]
Hi,

I tried to reproduce your error (mysql+node v8), but could not. Can you give me same more details? 
Like: when does it occur? On start up?

**Comment by Kadelam** [comment]
This happens every time the gallery is started with mysql as the db backend and only when I request a random picture with /api/gallery/random/
Running MariaDB 10.1.37 and node 11.2.0 currently but it was also borked with 11.1.0.

**Comment by bpatrik** [comment]
Thank you for the report, I managed to find the error.
With the latest commit ([5625f37](https://github.com/bpatrik/pigallery2/commit/5625f37d6b9602b951fd805d2d659bbf73b35dd5)) I fixed it. 
It will be part of the next (soon-comming) release.

**Comment by Kadelam** [comment]
I can confirm it's working. Cheers!
