### ISSUE TITLE
SQL Errors

### ISSUE THREAD

**Issue by palitu** [bpatrik/pigallery2#47]
I am getting a lot of these issues for a certain image.  It seems to hang the indexing as a result, by constantly retrying the image.

as you can see there is something weird with the altitude on that photo.

```
pigallery       |   name: 'QueryFailedError',
pigallery       |   query:
pigallery       |    'INSERT INTO `media_entity`(`id`, `name`, `type`, `directoryId`, `metadataCaption`, `metadataCreationdate`, `metadataFilesize`, `metadataKeywords`, `metadataOrientation`, `metadataBitrate`, `metadataDuration`, `metadataSizeWidth`, `metadataSizeHeight`, `metadataCameraDataIso`, `metadataCameraDataModel`, `metadataCameraDataMake`, `metadataCameraDataFstop`, `metadataCameraDataExposure`, `metadataCameraDataFocallength`, `metadataCameraDataLens`, `metadataPositionDataCountry`, `metadataPositionDataState`, `metadataPositionDataCity`, `metadataPositionDataGPSDataLatitude`, `metadataPositionDataGPSDataLongitude`, `metadataPositionDataGPSDataAltitude`) VALUES (DEFAULT, ?, ?, ?, DEFAULT, ?, ?, DEFAULT, ?, DEFAULT, DEFAULT, ?, ?, ?, ?, ?, ?, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT, ?, ?, ?)',
pigallery       |   parameters:
pigallery       |    [ 'IMG_20160307_115115.jpg',
pigallery       |      'PhotoEntity',
pigallery       |      20,
pigallery       |      1457351475000,
pigallery       |      2459130,
pigallery       |      1,
pigallery       |      3120,
pigallery       |      4160,
pigallery       |      112,
pigallery       |      'Redmi Note 2',
pigallery       |      'Xiaomi',
pigallery       |      2.2,
pigallery       |      0.000481,
pigallery       |      3.5,
pigallery       |      -32.58647536111111,
pigallery       |      115.74507138888889,
pigallery       |      4294967291 ] }
pigallery       | { QueryFailedError: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'metadataPositionDataGPSDataAltitude' at row 1
pigallery       |     at new QueryFailedError (/pigallery2-release/node_modules/typeorm/error/QueryFailedError.js:11:28)
pigallery       |     at Query.<anonymous> (/pigallery2-release/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:167:45)
pigallery       |     at Query.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:502:10)
pigallery       |     at Query._callback (/pigallery2-release/node_modules/mysql/lib/Connection.js:468:16)
pigallery       |     at Query.Sequence.end (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
pigallery       |     at Query.ErrorPacket (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
pigallery       |     at Protocol._parsePacket (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:278:23)
pigallery       |     at Parser.write (/pigallery2-release/node_modules/mysql/lib/protocol/Parser.js:76:12)
pigallery       |     at Protocol.write (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:38:16)
pigallery       |     at Socket.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:91:28)
pigallery       |   message:
pigallery       |    'ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column \'metadataPositionDataGPSDataAltitude\' at row 1',
pigallery       |   code: 'ER_WARN_DATA_OUT_OF_RANGE',
pigallery       |   errno: 1264,
pigallery       |   sqlMessage:
pigallery       |    'Out of range value for column \'metadataPositionDataGPSDataAltitude\' at row 1',
pigallery       |   sqlState: '22003',
pigallery       |   index: 0,
pigallery       |   sql:
pigallery       |    'INSERT INTO `media_entity`(`id`, `name`, `type`, `directoryId`, `metadataCaption`, `metadataCreationdate`, `metadataFilesize`, `metadataKeywords`, `metadataOrientation`, `metadataBitrate`, `metadataDuration`, `metadataSizeWidth`, `metadataSizeHeight`, `metadataCameraDataIso`, `metadataCameraDataModel`, `metadataCameraDataMake`, `metadataCameraDataFstop`, `metadataCameraDataExposure`, `metadataCameraDataFocallength`, `metadataCameraDataLens`, `metadataPositionDataCountry`, `metadataPositionDataState`, `metadataPositionDataCity`, `metadataPositionDataGPSDataLatitude`, `metadataPositionDataGPSDataLongitude`, `metadataPositionDataGPSDataAltitude`) VALUES (DEFAULT, \'IMG_20160307_115115.jpg\', \'PhotoEntity\', 20, DEFAULT, 1457351475000, 2459130, DEFAULT, 1, DEFAULT, DEFAULT, 3120, 4160, 112, \'Redmi Note 2\', \'Xiaomi\', 2.2, 0.000481, 3.5, DEFAULT, DEFAULT, DEFAULT, DEFAULT, -32.58647536111111, 115.74507138888889, 4294967291)',
```

**Comment by palitu** [comment]
hahah!

yeah, i am part of an amateur space exploration team, and so i have odd altitudes ;)

I'll grab the latest docker image and see what happens!  Did you change to bigint? or are you sanity checking values?

**Comment by palitu** [comment]
haha!  i was kidding!  perhaps i should put in a winky face.

I think that there may be more issues, with a similar bug - 

```
pigallery       |   name: 'QueryFailedError',
pigallery       |   query:
pigallery       |    'INSERT INTO `media_entity`(`id`, `name`, `type`, `directoryId`, `metadataCaption`, `metadataCreationdate`, `metadataFilesize`, `metadataKeywords`, `metadataOrientation`, `metadataBitrate`, `metadataDuration`, `metadataSizeWidth`, `metadataSizeHeight`, `metadataCameraDataIso`, `metadataCameraDataModel`, `metadataCameraDataMake`, `metadataCameraDataFstop`, `metadataCameraDataExposure`, `metadataCameraDataFocallength`, `metadataCameraDataLens`, `metadataPositionDataCountry`, `metadataPositionDataState`, `metadataPositionDataCity`, `metadataPositionDataGPSDataLatitude`, `metadataPositionDataGPSDataLongitude`, `metadataPositionDataGPSDataAltitude`) VALUES (DEFAULT, ?, ?, ?, DEFAULT, ?, ?, DEFAULT, DEFAULT, ?, ?, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT)',
pigallery       |   parameters:
pigallery       |    [ 'VID_20170914_205204.mp4',
pigallery       |      'VideoEntity',
pigallery       |      20,
pigallery       |      1505379127000,
pigallery       |      18912,
pigallery       |      10609200000,
pigallery       |      0,
pigallery       |      1280,
pigallery       |      720 ] }
pigallery       | { QueryFailedError: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'metadataBitrate' at row 1
pigallery       |     at new QueryFailedError (/pigallery2-release/node_modules/typeorm/error/QueryFailedError.js:11:28)
pigallery       |     at Query.<anonymous> (/pigallery2-release/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:167:45)
pigallery       |     at Query.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:502:10)
pigallery       |     at Query._callback (/pigallery2-release/node_modules/mysql/lib/Connection.js:468:16)
pigallery       |     at Query.Sequence.end (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
pigallery       |     at Query.ErrorPacket (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
pigallery       |     at Protocol._parsePacket (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:278:23)
pigallery       |     at Parser.write (/pigallery2-release/node_modules/mysql/lib/protocol/Parser.js:76:12)
pigallery       |     at Protocol.write (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:38:16)
pigallery       |     at Socket.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:91:28)
pigallery       |   message:
pigallery       |    'ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column \'metadataBitrate\' at row 1',
pigallery       |   code: 'ER_WARN_DATA_OUT_OF_RANGE',
pigallery       |   errno: 1264,
pigallery       |   sqlMessage: 'Out of range value for column \'metadataBitrate\' at row 1',
pigallery       |   sqlState: '22003',
pigallery       |   index: 0,
pigallery       |   sql:
pigallery       |    'INSERT INTO `media_entity`(`id`, `name`, `type`, `directoryId`, `metadataCaption`, `metadataCreationdate`, `metadataFilesize`, `metadataKeywords`, `metadataOrientation`, `metadataBitrate`, `metadataDuration`, `metadataSizeWidth`, `metadataSizeHeight`, `metadataCameraDataIso`, `metadataCameraDataModel`, `metadataCameraDataMake`, `metadataCameraDataFstop`, `metadataCameraDataExposure`, `metadataCameraDataFocallength`, `metadataCameraDataLens`, `metadataPositionDataCountry`, `metadataPositionDataState`, `metadataPositionDataCity`, `metadataPositionDataGPSDataLatitude`, `metadataPositionDataGPSDataLongitude`, `metadataPositionDataGPSDataAltitude`) VALUES (DEFAULT, \'VID_20170914_205204.mp4\', \'VideoEntity\', 20, DEFAULT, 1505379127000, 18912, DEFAULT, DEFAULT, 10609200000, 0, 1280, 720, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT)',
```

**Comment by bpatrik** [comment]
Oh you got me :)
Okay. I gave it an other try to fix. I hope it works this time.

**Comment by palitu** [comment]
Note that this is a different attribute!

**Comment by bpatrik** [comment]
I know.
Do you still get the error?

**Comment by bpatrik** [comment]
Can you confirm that this still exists?

**Comment by palitu** [comment]
i have not had any errors with it since the update, you can close it.
