### ISSUE TITLE
How to fix 'address not available'?

### ISSUE THREAD

**Issue by IanRawz** [bpatrik/pigallery2#477]
So I'm using a smb-share as a source for the pigallery2 gallery. I had everything up and running but had to remount the smb-share a few days ago. Wasn't sure how pigallery2 handles this kind of stuff so I thought it might be a good idea to stop pigallery2 first. I think I made a mistake by using `docker-compose stop` instead of `docker-compose down` because now I'm getting the following error everytime I try to start pigallery2 via `docker-compose up -d`:
```
pigallery2    | 4/19/2022, 7:48:55 PM[INFO_][server] running diagnostics...
pigallery2    | 4/19/2022, 7:48:55 PM[INFO_][JobManager] Running job schedules
pigallery2    | /app/src/backend/server.js:59
pigallery2    |                     throw error;
pigallery2    |                     ^
pigallery2    |
pigallery2    | Error: listen EADDRNOTAVAIL: address not available 192.168.2.40:80
pigallery2    |     at Server.setupListenHandle [as _listen2] (net.js:1314:21)
pigallery2    |     at listenInCluster (net.js:1379:12)
pigallery2    |     at doListen (net.js:1516:7)
pigallery2    |     at processTicksAndRejections (internal/process/task_queues.js:83:21) {
pigallery2    |   code: 'EADDRNOTAVAIL',
pigallery2    |   errno: -99,
pigallery2    |   syscall: 'listen',
pigallery2    |   address: '192.168.2.40',
pigallery2    |   port: 80
pigallery2    | }
```
The 192.168.2.40 address is the ip of my windows main machine, not sure if that's the reason why it says 'address not available'.

How can I fix this now?

**Comment by bpatrik** [comment]
My guess would be a reboot will do it.

Most likely docker did not release your port, so you cannot reclaim it after you restart.
You can also try using `netstat` command to figure out what uses which port. (google for manual and usage examples)

**Comment by bpatrik** [comment]
closing this due to inactivity
