### ISSUE TITLE
Duplicate Key error on index

### ISSUE THREAD

**Issue by palitu** [bpatrik/pigallery2#49]
Sorry... i have another one....
looks like it has generated a duplicate key, which seems... rare!

It seemed to continually try to re insert the image, without re-calculating the key.  I'm not sure if it continued to index or not, as there is not a lot of stout logging.

```
pigallery       |   name: 'QueryFailedError',
pigallery       |   query:
pigallery       |    'INSERT INTO `media_entity`(`id`, `name`, `type`, `directoryId`, `metadataCaption`, `metadataCreationdate`, `metadataFilesize`, `metadataKeywords`, `metadataOrientation`, `metadataBitrate`, `metadataDuration`, `metadataSizeWidth`, `metadataSizeHeight`, `metadataCameraDataIso`, `metadataCameraDataModel`, `metadataCameraDataMake`, `metadataCameraDataFstop`, `metadataCameraDataExposure`, `metadataCameraDataFocallength`, `metadataCameraDataLens`, `metadataPositionDataCountry`, `metadataPositionDataState`, `metadataPositionDataCity`, `metadataPositionDataGPSDataLatitude`, `metadataPositionDataGPSDataLongitude`, `metadataPositionDataGPSDataAltitude`) VALUES (DEFAULT, ?, ?, ?, DEFAULT, ?, ?, ?, ?, DEFAULT, DEFAULT, ?, ?, ?, ?, ?, ?, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT, ?, ?, ?)',
pigallery       |   parameters:
pigallery       |    [ 'IMG_0995.jpg',
pigallery       |      'PhotoEntity',
pigallery       |      103,
pigallery       |      1323184378000,
pigallery       |      2198584,
pigallery       |      '',
pigallery       |      1,
pigallery       |      2592,
pigallery       |      1936,
pigallery       |      80,
pigallery       |      'iPhone 4',
pigallery       |      'Apple',
pigallery       |      2.8,
pigallery       |      0.058823529411764705,
pigallery       |      3.85,
pigallery       |      -32.04533333333333,
pigallery       |      115.81633333333333,
pigallery       |      31.19884726224784 ] }
pigallery       | { QueryFailedError: ER_DUP_ENTRY: Duplicate entry 'IMG_0995.jpg-103' for key 'IDX_332f316a46fcb158ac71210109'
pigallery       |     at new QueryFailedError (/pigallery2-release/node_modules/typeorm/error/QueryFailedError.js:11:28)
pigallery       |     at Query.<anonymous> (/pigallery2-release/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:167:45)
pigallery       |     at Query.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:502:10)
pigallery       |     at Query._callback (/pigallery2-release/node_modules/mysql/lib/Connection.js:468:16)
pigallery       |     at Query.Sequence.end (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
pigallery       |     at Query.ErrorPacket (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
pigallery       |     at Protocol._parsePacket (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:278:23)
pigallery       |     at Parser.write (/pigallery2-release/node_modules/mysql/lib/protocol/Parser.js:76:12)
pigallery       |     at Protocol.write (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:38:16)
pigallery       |     at Socket.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:91:28)
pigallery       |   message:
pigallery       |    'ER_DUP_ENTRY: Duplicate entry \'IMG_0995.jpg-103\' for key \'IDX_332f316a46fcb158ac71210109\'',
pigallery       |   code: 'ER_DUP_ENTRY',
pigallery       |   errno: 1062,
pigallery       |   sqlMessage:
pigallery       |    'Duplicate entry \'IMG_0995.jpg-103\' for key \'IDX_332f316a46fcb158ac71210109\'',
pigallery       |   sqlState: '23000',
pigallery       |   index: 0,
pigallery       |   sql:
pigallery       |    'INSERT INTO `media_entity`(`id`, `name`, `type`, `directoryId`, `metadataCaption`, `metadataCreationdate`, `metadataFilesize`, `metadataKeywords`, `metadataOrientation`, `metadataBitrate`, `metadataDuration`, `metadataSizeWidth`, `metadataSizeHeight`, `metadataCameraDataIso`, `metadataCameraDataModel`, `metadataCameraDataMake`, `metadataCameraDataFstop`, `metadataCameraDataExposure`, `metadataCameraDataFocallength`, `metadataCameraDataLens`, `metadataPositionDataCountry`, `metadataPositionDataState`, `metadataPositionDataCity`, `metadataPositionDataGPSDataLatitude`, `metadataPositionDataGPSDataLongitude`, `metadataPositionDataGPSDataAltitude`) VALUES (DEFAULT, \'IMG_0995.jpg\', \'PhotoEntity\', 103, DEFAULT, 1323184378000, 2198584, \'\', 1, DEFAULT, DEFAULT, 2592, 1936, 80, \'iPhone 4\', \'Apple\', 2.8, 0.058823529411764705, 3.85, DEFAULT, DEFAULT, DEFAULT, DEFAULT, -32.04533333333333, 115.81633333333333, 31.19884726224784)',
```

**Comment by bpatrik** [comment]
Is that possible that you have the same file name `IMG_0995.jpg` twice in one folder (folder with DB id `103`) ? 
I think its a 'fatal' error, as I really don't want to anything like this to happen, so the indexing stops.

No problem. TBH I never used the mysql version of the app, so it might have bugs. Thank you for helping me debugging it.

**Comment by palitu** [comment]
there is potential that there is the same photo name, but it is `.jpg` vs `.JPG`.

in stead of killing the indexing, and hence stopping the rest of the photos, is it possible to skip that file?

I'm happy to help, but perhaps we can have a setting for more verbose logging?  I generally just sit there watch for a failure, and it is hard to see what happens when there is a failure.

**Comment by palitu** [comment]
they are the same photo, with the same name, but one is lowercase, and one is upper case.  Both in the same folder.


![screenshot_20190207_214924](https://user-images.githubusercontent.com/6634784/52415871-2cfae280-2b23-11e9-80fc-0bea29e5a5a7.png)

**Comment by bpatrik** [comment]
Hi,

Thank you for the details!

I made a commit to fix the case sensitivity in MySQL.
I've also added logging settings to the config. 

You can use them like this:
```typescript
export enum LogLevel {
  error = 1, warn = 2, info = 3, debug = 4, verbose = 5
}

export enum SQLLogLevel {
  none = 1, error = 2, all = 3
}
```
in `config.json`:
```
  "Server": {
    "log": {
      "level": 1,
      "sqlLevel": 1
    },
...
}
```

Note: wait until the docker finishes building

**Comment by palitu** [comment]
perfect!  thanks.  I have been flat out the last couple of days, but i will look at it over the weekend hopefully!

**Comment by palitu** [comment]
all indexed!

![screenshot_20190208_181712](https://user-images.githubusercontent.com/6634784/52520647-9ce5a600-2ca6-11e9-83e1-8baaded883c7.png)

**Comment by bpatrik** [comment]
Perfect!
