### ISSUE TITLE
SQL error when i execute indexer

### ISSUE THREAD

**Issue by Railline** [bpatrik/pigallery2#559]
**Describe the bug**

When the indexer runing on my folder
they don't write one of my sub folder in the database
**Photo/video (optional) that causes the bug**

[xmldom warning]        unclosed xml attribute 
@#[line:1,col:1]
[xmldom warning]        unclosed xml attribute 
@#[line:2,col:4]
[xmldom warning]        unclosed xml attribute 
@#[line:3,col:7]
[xmldom warning]        unclosed xml attribute 
@#[line:6,col:10]
QueryFailedError: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'mediaCount' at row 1
    at QueryFailedError.TypeORMError [as constructor] (/app/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/app/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at Query.<anonymous> (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:193:57)
    at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/app/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  query: 'UPDATE `directory_entity` SET `lastScanned` = ?, `mediaCount` = ? WHERE `id` IN (?)',
  parameters: [ 1669058734767, 67160, 48 ],
  driverError: Error: ER_WARN_DATA_OUT_OF_RANGE: Out of range value for column 'mediaCount' at row 1
      at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
      at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
      at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
      at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
      at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
      at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
      at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
      at Socket.emit (events.js:400:28)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      --------------------
      at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
      at PoolConnection.query (/app/node_modules/mysql/lib/Connection.js:198:25)
      at MysqlQueryRunner.<anonymous> (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:184:56)
      at step (/app/node_modules/tslib/tslib.js:143:27)
      at Object.next (/app/node_modules/tslib/tslib.js:124:57)
      at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    code: 'ER_WARN_DATA_OUT_OF_RANGE',
    errno: 1264,
    sqlMessage: "Out of range value for column 'mediaCount' at row 1",
    sqlState: '22003',
    index: 0,
    sql: 'UPDATE `directory_entity` SET `lastScanned` = 1669058734767, `mediaCount` = 67160 WHERE `id` IN (48)'
  },
  code: 'ER_WARN_DATA_OUT_OF_RANGE',
  errno: 1264,
  sqlMessage: "Out of range value for column 'mediaCount' at row 1",
  sqlState: '22003',
  index: 0,
  sql: 'UPDATE `directory_entity` SET `lastScanned` = 1669058734767, `mediaCount` = 67160 WHERE `id` IN (48)'
}

**Server logs (optional)**

In case of a server side error, provide logs:
* Set env variable `NODE_ENV=debug` to log everything.
* To get logs from docker: `docker ps -a` to list containers, `docker logs <container ID>` to get logs.

**Environment (please complete the following information):**
 - OS: Unraid (Docker)
 - Browser chrome

**Used app version**: docker-latest

**Comment by bpatrik** [comment]
increased the max folder size to 16777215 from 65535. nightly build contain it once it builds.
