### ISSUE TITLE
How to use Users-enforcedUsers in environment?

### ISSUE THREAD

**Issue by mrtnbr** [bpatrik/pigallery2#575]
**Describe the bug**

I am trying to use Users-enforcedUsers ENV variable (via docker-compose) to create/enforce a user. Is this supported?

I'm not sure how to do it, I tried some variations but could not get it to work. 

'''
    environment:
      - TZ=Europe/Amsterdam
      - NODE_ENV=debug
      - Server-applicationTitle=TESTING
      - Media-Photo-supportedFormats=["gif","jpeg","jpg","jpe","png","webp","svg","tif"]
      - Users-enforcedUsers=["testuser"]
'''

**Server logs (optional)**

In case of a server side error, provide logs:
Error from log:
```
pigallery2_testing  | 1/6/2023, 10:46:48 AM[INFO_][SQLConnection] Saving enforced user: undefined
pigallery2_testing  | QueryFailedError: SqliteError: NOT NULL constraint failed: user_entity.name
pigallery2_testing  |     at BetterSqlite3QueryRunner.query (/app/node_modules/typeorm/driver/better-sqlite3/BetterSqlite3QueryRunner.js:109:19)
pigallery2_testing  |     at async InsertQueryBuilder.execute (/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
pigallery2_testing  |     at async SubjectExecutor.executeInsertOperations (/app/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
pigallery2_testing  |     at async SubjectExecutor.execute (/app/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
pigallery2_testing  |     at async EntityPersistExecutor.execute (/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:147:21)
pigallery2_testing  |     at async SQLConnection.init (/app/src/backend/model/database/SQLConnection.js:117:21)
pigallery2_testing  |     at async ObjectManagers.InitSQLManagers (/app/src/backend/model/ObjectManagers.js:154:9)
pigallery2_testing  |     at async Server.init (/app/src/backend/server.js:109:9) {
pigallery2_testing  |   query: 'INSERT INTO "user_entity"("id", "name", "password", "role", "permissions") VALUES (NULL, NULL, NULL, 3, NULL)',
pigallery2_testing  |   parameters: [],
pigallery2_testing  |   driverError: SqliteError: NOT NULL constraint failed: user_entity.name
pigallery2_testing  |       at BetterSqlite3QueryRunner.query (/app/node_modules/typeorm/driver/better-sqlite3/BetterSqlite3QueryRunner.js:91:38)
pigallery2_testing  |       at async InsertQueryBuilder.execute (/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
pigallery2_testing  |       at async SubjectExecutor.executeInsertOperations (/app/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
pigallery2_testing  |       at async SubjectExecutor.execute (/app/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
pigallery2_testing  |       at async EntityPersistExecutor.execute (/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:147:21)
pigallery2_testing  |       at async SQLConnection.init (/app/src/backend/model/database/SQLConnection.js:117:21)
pigallery2_testing  |       at async ObjectManagers.InitSQLManagers (/app/src/backend/model/ObjectManagers.js:154:9)
pigallery2_testing  |       at async Server.init (/app/src/backend/server.js:109:9) {
pigallery2_testing  |     code: 'SQLITE_CONSTRAINT_NOTNULL'
pigallery2_testing  |   },
pigallery2_testing  |   code: 'SQLITE_CONSTRAINT_NOTNULL'
pigallery2_testing  | }
```
More log:
```
Showing logs for the following service(s): pigallery2_testing 
PID=499036 
pigallery2_testing  | [Typeconfig] Loading config. Path: /app/data/config/config.json
pigallery2_testing  | [Typeconfig] Loading defaults from file: undefined
pigallery2_testing  | [Typeconfig] Loading defaults, def prefix: default
pigallery2_testing  | [Typeconfig] no default cli found among these: {
pigallery2_testing  |   "expose": {
pigallery2_testing  |           "gc": true
pigallery2_testing  |   },
pigallery2_testing  |   "config": {
pigallery2_testing  |           "path": "/app/data/config/config.json"
pigallery2_testing  |   }
pigallery2_testing  | }
pigallery2_testing  | [Typeconfig] from env: {
pigallery2_testing  |   "Database": {
pigallery2_testing  |           "dbFolder": "/app/data/db"
pigallery2_testing  |   },
pigallery2_testing  |   "Media": {
pigallery2_testing  |           "folder": "/app/data/images",
pigallery2_testing  |           "tempFolder": "/app/data/tmp"
pigallery2_testing  |   }
pigallery2_testing  | }
pigallery2_testing  | [Typeconfig] Processing cli and ENV inputs: {
pigallery2_testing  |   "expose": {
pigallery2_testing  |           "gc": true
pigallery2_testing  |   },
pigallery2_testing  |   "config": {
pigallery2_testing  |           "path": "/app/data/config/config.json"
pigallery2_testing  |   }
pigallery2_testing  | }
pigallery2_testing  | [Typeconfig] Processing cli and ENV inputs: {
pigallery2_testing  |   "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
pigallery2_testing  |   "HOSTNAME": "pigallery2_testing",
pigallery2_testing  |   "Server": {
pigallery2_testing  |           "applicationTitle": "TESTING"
pigallery2_testing  |   },
pigallery2_testing  |   "Media": {
pigallery2_testing  |           "Photo": {
pigallery2_testing  |                   "supportedFormats": "[\"gif\",\"jpeg\",\"jpg\",\"jpe\",\"png\",\"webp\",\"svg\",\"tif\"]"
pigallery2_testing  |           }
pigallery2_testing  |   },
pigallery2_testing  |   "Users": {
pigallery2_testing  |           "enforcedUsers": "[\"testuser\"]"
pigallery2_testing  |   },
pigallery2_testing  |   "TZ": "Europe/Amsterdam",
pigallery2_testing  |   "NODE_ENV": "debug",
pigallery2_testing  |   "NODE_VERSION": "18.12.1",
pigallery2_testing  |   "YARN_VERSION": "1.22.19",
pigallery2_testing  |   "PI_DOCKER": true,
pigallery2_testing  |   "HOME": "/root"
pigallery2_testing  | }
pigallery2_testing  | NODE_ENV environmental variable is set to debug, forcing all logs to print
pigallery2_testing  | 1/6/2023, 10:46:48 AM[INFO_][server] Running in DEBUG mode, set env variable NODE_ENV=production to disable 
pigallery2_testing  | 1/6/2023, 10:46:48 AM[INFO_][server] running diagnostics...
pigallery2_testing  | 1/6/2023, 10:46:48 AM[VERBS][server] using config from /app/data/config/config.json:
pigallery2_testing  | 1/6/2023, 10:46:48 AM[VERBS][server] {
pigallery2_testing  |   "Server": {
pigallery2_testing  |           "applicationTitle": "TESTING",
pigallery2_testing  |           "publicUrl": "",
pigallery2_testing  |           "urlBase": "",
pigallery2_testing  |           "apiPath": "/pgapi",
pigallery2_testing  |           "customHTMLHead": "",
pigallery2_testing  |           "sessionSecret": [
<snip>
pigallery2_testing  |           ],
pigallery2_testing  |           "sessionTimeout": 604800000,
pigallery2_testing  |           "port": 80,
pigallery2_testing  |           "host": "0.0.0.0",
pigallery2_testing  |           "Threading": {
pigallery2_testing  |                   "enabled": true,
pigallery2_testing  |                   "thumbnailThreads": 0
pigallery2_testing  |           },
pigallery2_testing  |           "Log": {
pigallery2_testing  |                   "level": 3,
pigallery2_testing  |                   "sqlLevel": 2,
pigallery2_testing  |                   "logServerTiming": false
pigallery2_testing  |           }
pigallery2_testing  |   },
pigallery2_testing  |   "Users": {
pigallery2_testing  |           "authenticationRequired": true,
pigallery2_testing  |           "unAuthenticatedUserRole": 4,
pigallery2_testing  |           "enforcedUsers": [
pigallery2_testing  |                   {
pigallery2_testing  |                           "role": 3
pigallery2_testing  |                   }
pigallery2_testing  |           ]
pigallery2_testing  |   },
pigallery2_testing  |   "Gallery": {
pigallery2_testing  |           "enableCache": true,
pigallery2_testing  |           "enableOnScrollRendering": true,
pigallery2_testing  |           "defaultPhotoSortingMethod": 3,
pigallery2_testing  |           "defaultSearchSortingMethod": 4,
pigallery2_testing  |           "enableDirectorySortingByDate": false,
pigallery2_testing  |           "enableOnScrollThumbnailPrioritising": true,
pigallery2_testing  |           "NavBar": {
pigallery2_testing  |                   "showItemCount": true,
pigallery2_testing  |                   "links": [
pigallery2_testing  |                           {
pigallery2_testing  |                                   "type": 1
pigallery2_testing  |                           },
pigallery2_testing  |                           {
pigallery2_testing  |                                   "type": 3
pigallery2_testing  |                           },
pigallery2_testing  |                           {
pigallery2_testing  |                                   "type": 2
pigallery2_testing  |                           }
pigallery2_testing  |                   ]
pigallery2_testing  |           },
pigallery2_testing  |           "captionFirstNaming": false,
pigallery2_testing  |           "enableDownloadZip": false,
pigallery2_testing  |           "enableDirectoryFlattening": false,
pigallery2_testing  |           "defaultSlideshowSpeed": 5
pigallery2_testing  |   },
pigallery2_testing  |   "Media": {
pigallery2_testing  |           "Thumbnail": {
pigallery2_testing  |                   "iconSize": 45,
pigallery2_testing  |                   "personThumbnailSize": 200,
pigallery2_testing  |                   "thumbnailSizes": [
pigallery2_testing  |                           240,
pigallery2_testing  |                           480
pigallery2_testing  |                   ],
pigallery2_testing  |                   "useLanczos3": true,
pigallery2_testing  |                   "quality": 80,
pigallery2_testing  |                   "personFaceMargin": 0.6
pigallery2_testing  |           },
pigallery2_testing  |           "Video": {
pigallery2_testing  |                   "enabled": true,
pigallery2_testing  |                   "supportedFormatsWithTranscoding": [
pigallery2_testing  |                           "avi",
pigallery2_testing  |                           "mkv",
pigallery2_testing  |                           "mov",
pigallery2_testing  |                           "wmv",
pigallery2_testing  |                           "flv",
pigallery2_testing  |                           "mts",
pigallery2_testing  |                           "m2ts",
pigallery2_testing  |                           "mpg",
pigallery2_testing  |                           "3gp",
pigallery2_testing  |                           "m4v",
pigallery2_testing  |                           "mpeg",
pigallery2_testing  |                           "vob",
pigallery2_testing  |                           "divx",
pigallery2_testing  |                           "xvid",
pigallery2_testing  |                           "ts"
pigallery2_testing  |                   ],
pigallery2_testing  |                   "supportedFormats": [
pigallery2_testing  |                           "mp4",
pigallery2_testing  |                           "webm",
pigallery2_testing  |                           "ogv",
pigallery2_testing  |                           "ogg"
pigallery2_testing  |                   ],
pigallery2_testing  |                   "transcoding": {
pigallery2_testing  |                           "bitRate": 5242880,
pigallery2_testing  |                           "resolution": 720,
pigallery2_testing  |                           "fps": 25,
pigallery2_testing  |                           "format": "mp4",
pigallery2_testing  |                           "mp4Codec": "libx264",
pigallery2_testing  |                           "webmCodec": "libvpx",
pigallery2_testing  |                           "crf": 23,
pigallery2_testing  |                           "preset": 6,
pigallery2_testing  |                           "customOptions": []
pigallery2_testing  |                   }
pigallery2_testing  |           },
pigallery2_testing  |           "Photo": {
pigallery2_testing  |                   "Converting": {
pigallery2_testing  |                           "enabled": true,
pigallery2_testing  |                           "loadFullImageOnZoom": true,
pigallery2_testing  |                           "onTheFly": true,
pigallery2_testing  |                           "resolution": 1080
pigallery2_testing  |                   },
pigallery2_testing  |                   "supportedFormats": [
pigallery2_testing  |                           "gif",
pigallery2_testing  |                           "jpeg",
pigallery2_testing  |                           "jpg",
pigallery2_testing  |                           "jpe",
pigallery2_testing  |                           "png",
pigallery2_testing  |                           "webp",
pigallery2_testing  |                           "svg",
pigallery2_testing  |                           "tif"
pigallery2_testing  |                   ]
pigallery2_testing  |           },
pigallery2_testing  |           "folder": "/app/data/images",
pigallery2_testing  |           "tempFolder": "/app/data/tmp",
pigallery2_testing  |           "photoMetadataSize": 524288
pigallery2_testing  |   },
pigallery2_testing  |   "MetaFile": {
pigallery2_testing  |           "gpx": true,
pigallery2_testing  |           "GPXCompressing": {
pigallery2_testing  |                   "enabled": true,
pigallery2_testing  |                   "onTheFly": true,
pigallery2_testing  |                   "minDistance": 5,
pigallery2_testing  |                   "minTimeDistance": 5000
pigallery2_testing  |           },
pigallery2_testing  |           "markdown": true,
pigallery2_testing  |           "pg2conf": true,
pigallery2_testing  |           "supportedFormats": [
pigallery2_testing  |                   "gpx",
pigallery2_testing  |                   "pg2conf",
pigallery2_testing  |                   "md"
pigallery2_testing  |           ]
pigallery2_testing  |   },
pigallery2_testing  |   "Album": {
pigallery2_testing  |           "enabled": true
pigallery2_testing  |   },
pigallery2_testing  |   "Search": {
pigallery2_testing  |           "enabled": true,
pigallery2_testing  |           "searchCacheTimeout": 3600000,
pigallery2_testing  |           "AutoComplete": {
pigallery2_testing  |                   "enabled": true,
pigallery2_testing  |                   "targetItemsPerCategory": 5,
pigallery2_testing  |                   "maxItems": 30,
pigallery2_testing  |                   "cacheTimeout": 3600000
pigallery2_testing  |           },
pigallery2_testing  |           "maxMediaResult": 10000,
pigallery2_testing  |           "maxDirectoryResult": 200,
pigallery2_testing  |           "listDirectories": false,
pigallery2_testing  |           "listMetafiles": true
pigallery2_testing  |   },
pigallery2_testing  |   "Sharing": {
pigallery2_testing  |           "enabled": true,
pigallery2_testing  |           "passwordProtected": true,
pigallery2_testing  |           "updateTimeout": 300000
pigallery2_testing  |   },
pigallery2_testing  |   "Map": {
pigallery2_testing  |           "enabled": true,
pigallery2_testing  |           "useImageMarkers": true,
pigallery2_testing  |           "mapProvider": 1,
pigallery2_testing  |           "mapboxAccessToken": "",
pigallery2_testing  |           "customLayers": [
pigallery2_testing  |                   {
pigallery2_testing  |                           "name": "street",
pigallery2_testing  |                           "url": ""
pigallery2_testing  |                   }
pigallery2_testing  |           ],
pigallery2_testing  |           "maxPreviewMarkers": 50
pigallery2_testing  |   },
pigallery2_testing  |   "Faces": {
pigallery2_testing  |           "enabled": true,
pigallery2_testing  |           "keywordsToPersons": true,
pigallery2_testing  |           "writeAccessMinRole": 4,
pigallery2_testing  |           "readAccessMinRole": 3
pigallery2_testing  |   },
pigallery2_testing  |   "RandomPhoto": {
pigallery2_testing  |           "enabled": true
pigallery2_testing  |   },
pigallery2_testing  |   "Database": {
pigallery2_testing  |           "type": 3,
pigallery2_testing  |           "dbFolder": "/app/data/db",
pigallery2_testing  |           "sqlite": {
pigallery2_testing  |                   "DBFileName": "sqlite.db"
pigallery2_testing  |           },
pigallery2_testing  |           "mysql": {
pigallery2_testing  |                   "host": "localhost",
pigallery2_testing  |                   "port": 3306,
pigallery2_testing  |                   "database": "pigallery2",
pigallery2_testing  |                   "username": "",
pigallery2_testing  |                   "password": ""
pigallery2_testing  |           }
pigallery2_testing  |   },
pigallery2_testing  |   "Indexing": {
pigallery2_testing  |           "cachedFolderTimeout": 3600000,
pigallery2_testing  |           "reIndexingSensitivity": 1,
pigallery2_testing  |           "excludeFolderList": [
pigallery2_testing  |                   ".Trash-1000",
pigallery2_testing  |                   ".dtrash",
pigallery2_testing  |                   "$RECYCLE.BIN"
pigallery2_testing  |           ],
pigallery2_testing  |           "excludeFileList": []
pigallery2_testing  |   },
pigallery2_testing  |   "Preview": {
pigallery2_testing  |           "SearchQuery": {
pigallery2_testing  |                   "type": 100,
pigallery2_testing  |                   "text": ""
pigallery2_testing  |           },
pigallery2_testing  |           "Sorting": [
pigallery2_testing  |                   6,
pigallery2_testing  |                   4
pigallery2_testing  |           ]
pigallery2_testing  |   },
pigallery2_testing  |   "Duplicates": {
pigallery2_testing  |           "listingLimit": 1000
pigallery2_testing  |   },
pigallery2_testing  |   "Jobs": {
pigallery2_testing  |           "maxSavedProgress": 20,
pigallery2_testing  |           "mediaProcessingBatchSize": 1000,
pigallery2_testing  |           "scheduled": [
pigallery2_testing  |                   {
pigallery2_testing  |                           "name": "Indexing",
pigallery2_testing  |                           "jobName": "Indexing",
pigallery2_testing  |                           "config": {
pigallery2_testing  |                                   "indexChangesOnly": true
pigallery2_testing  |                           },
pigallery2_testing  |                           "allowParallelRun": false,
pigallery2_testing  |                           "trigger": {
pigallery2_testing  |                                   "type": 1
pigallery2_testing  |                           }
pigallery2_testing  |                   },
pigallery2_testing  |                   {
pigallery2_testing  |                           "name": "Preview Filling",
pigallery2_testing  |                           "jobName": "Preview Filling",
pigallery2_testing  |                           "config": {},
pigallery2_testing  |                           "allowParallelRun": false,
pigallery2_testing  |                           "trigger": {
pigallery2_testing  |                                   "type": 4,
pigallery2_testing  |                                   "afterScheduleName": "Indexing"
pigallery2_testing  |                           }
pigallery2_testing  |                   },
pigallery2_testing  |                   {
pigallery2_testing  |                           "name": "Thumbnail Generation",
pigallery2_testing  |                           "jobName": "Thumbnail Generation",
pigallery2_testing  |                           "config": {
pigallery2_testing  |                                   "sizes": [
pigallery2_testing  |                                           240
pigallery2_testing  |                                   ],
pigallery2_testing  |                                   "indexedOnly": true
pigallery2_testing  |                           },
pigallery2_testing  |                           "allowParallelRun": false,
pigallery2_testing  |                           "trigger": {
pigallery2_testing  |                                   "type": 4,
pigallery2_testing  |                                   "afterScheduleName": "Preview Filling"
pigallery2_testing  |                           }
pigallery2_testing  |                   },
pigallery2_testing  |                   {
pigallery2_testing  |                           "name": "Photo Converting",
pigallery2_testing  |                           "jobName": "Photo Converting",
pigallery2_testing  |                           "config": {
pigallery2_testing  |                                   "indexedOnly": true
pigallery2_testing  |                           },
pigallery2_testing  |                           "allowParallelRun": false,
pigallery2_testing  |                           "trigger": {
pigallery2_testing  |                                   "type": 4,
pigallery2_testing  |                                   "afterScheduleName": "Thumbnail Generation"
pigallery2_testing  |                           }
pigallery2_testing  |                   },
pigallery2_testing  |                   {
pigallery2_testing  |                           "name": "Video Converting",
pigallery2_testing  |                           "jobName": "Video Converting",
pigallery2_testing  |                           "config": {
pigallery2_testing  |                                   "indexedOnly": true
pigallery2_testing  |                           },
pigallery2_testing  |                           "allowParallelRun": false,
pigallery2_testing  |                           "trigger": {
pigallery2_testing  |                                   "type": 4,
pigallery2_testing  |                                   "afterScheduleName": "Photo Converting"
pigallery2_testing  |                           }
pigallery2_testing  |                   },
pigallery2_testing  |                   {
pigallery2_testing  |                           "name": "GPX Compression",
pigallery2_testing  |                           "jobName": "GPX Compression",
pigallery2_testing  |                           "config": {
pigallery2_testing  |                                   "indexedOnly": true
pigallery2_testing  |                           },
pigallery2_testing  |                           "allowParallelRun": false,
pigallery2_testing  |                           "trigger": {
pigallery2_testing  |                                   "type": 4,
pigallery2_testing  |                                   "afterScheduleName": "Video Converting"
pigallery2_testing  |                           }
pigallery2_testing  |                   },
pigallery2_testing  |                   {
pigallery2_testing  |                           "name": "Temp Folder Cleaning",
pigallery2_testing  |                           "jobName": "Temp Folder Cleaning",
pigallery2_testing  |                           "config": {
pigallery2_testing  |                                   "indexedOnly": true
pigallery2_testing  |                           },
pigallery2_testing  |                           "allowParallelRun": false,
pigallery2_testing  |                           "trigger": {
pigallery2_testing  |                                   "type": 4,
pigallery2_testing  |                                   "afterScheduleName": "GPX Compression"
pigallery2_testing  |                           }
pigallery2_testing  |                   }
pigallery2_testing  |           ]
pigallery2_testing  |   }
pigallery2_testing  | }
pigallery2_testing  | 1/6/2023, 10:46:48 AM[SILLY][ThreadPool] Creating thread pool with 1 workers
pigallery2_testing  | 1/6/2023, 10:46:48 AM[SILLY][ObjectManagers] Object manager reset begin
pigallery2_testing  | 1/6/2023, 10:46:48 AM[DEBUG][ObjectManagers] Object manager reset
pigallery2_testing  | 1/6/2023, 10:46:48 AM[DEBUG][SQLConnection] Creating connection: sqlite , with driver: better-sqlite3
pigallery2_testing  | 1/6/2023, 10:46:48 AM[INFO_][SQLConnection] Saving enforced user: undefined
pigallery2_testing  | QueryFailedError: SqliteError: NOT NULL constraint failed: user_entity.name
pigallery2_testing  |     at BetterSqlite3QueryRunner.query (/app/node_modules/typeorm/driver/better-sqlite3/BetterSqlite3QueryRunner.js:109:19)
pigallery2_testing  |     at async InsertQueryBuilder.execute (/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
pigallery2_testing  |     at async SubjectExecutor.executeInsertOperations (/app/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
pigallery2_testing  |     at async SubjectExecutor.execute (/app/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
pigallery2_testing  |     at async EntityPersistExecutor.execute (/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:147:21)
pigallery2_testing  |     at async SQLConnection.init (/app/src/backend/model/database/SQLConnection.js:117:21)
pigallery2_testing  |     at async ObjectManagers.InitSQLManagers (/app/src/backend/model/ObjectManagers.js:154:9)
pigallery2_testing  |     at async Server.init (/app/src/backend/server.js:109:9) {
pigallery2_testing  |   query: 'INSERT INTO "user_entity"("id", "name", "password", "role", "permissions") VALUES (NULL, NULL, NULL, 3, NULL)',
pigallery2_testing  |   parameters: [],
pigallery2_testing  |   driverError: SqliteError: NOT NULL constraint failed: user_entity.name
pigallery2_testing  |       at BetterSqlite3QueryRunner.query (/app/node_modules/typeorm/driver/better-sqlite3/BetterSqlite3QueryRunner.js:91:38)
pigallery2_testing  |       at async InsertQueryBuilder.execute (/app/node_modules/typeorm/query-builder/InsertQueryBuilder.js:106:33)
pigallery2_testing  |       at async SubjectExecutor.executeInsertOperations (/app/node_modules/typeorm/persistence/SubjectExecutor.js:260:42)
pigallery2_testing  |       at async SubjectExecutor.execute (/app/node_modules/typeorm/persistence/SubjectExecutor.js:92:9)
pigallery2_testing  |       at async EntityPersistExecutor.execute (/app/node_modules/typeorm/persistence/EntityPersistExecutor.js:147:21)
pigallery2_testing  |       at async SQLConnection.init (/app/src/backend/model/database/SQLConnection.js:117:21)
pigallery2_testing  |       at async ObjectManagers.InitSQLManagers (/app/src/backend/model/ObjectManagers.js:154:9)
pigallery2_testing  |       at async Server.init (/app/src/backend/server.js:109:9) {
pigallery2_testing  |     code: 'SQLITE_CONSTRAINT_NOTNULL'
pigallery2_testing  |   },
pigallery2_testing  |   code: 'SQLITE_CONSTRAINT_NOTNULL'
pigallery2_testing  | }
pigallery2_testing  | 1/6/2023, 10:46:48 AM[DEBUG][ThreadPool] Worker 19 is online, worker count: 1
pigallery2_testing  | [Typeconfig] Loading config. Path: /app/data/config/config.json
pigallery2_testing  | [Typeconfig] Loading defaults from file: undefined
pigallery2_testing  | [Typeconfig] Loading defaults, def prefix: default
pigallery2_testing  | [Typeconfig] no default cli found among these: {
pigallery2_testing  |   "expose": {
pigallery2_testing  |           "gc": true
pigallery2_testing  |   },
pigallery2_testing  |   "config": {
pigallery2_testing  |           "path": "/app/data/config/config.json"
pigallery2_testing  |   }
pigallery2_testing  | }
pigallery2_testing  | [Typeconfig] from env: {
pigallery2_testing  |   "Database": {
pigallery2_testing  |           "dbFolder": "/app/data/db"
pigallery2_testing  |   },
pigallery2_testing  |   "Media": {
pigallery2_testing  |           "folder": "/app/data/images",
pigallery2_testing  |           "tempFolder": "/app/data/tmp"
pigallery2_testing  |   }
pigallery2_testing  | }
pigallery2_testing  | [Typeconfig] Processing cli and ENV inputs: {
pigallery2_testing  |   "expose": {
pigallery2_testing  |           "gc": true
pigallery2_testing  |   },
pigallery2_testing  |   "config": {
pigallery2_testing  |           "path": "/app/data/config/config.json"
pigallery2_testing  |   }
pigallery2_testing  | }
pigallery2_testing  | [Typeconfig] Processing cli and ENV inputs: {
pigallery2_testing  |   "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
pigallery2_testing  |   "HOSTNAME": "pigallery2_testing",
pigallery2_testing  |   "Server": {
pigallery2_testing  |           "applicationTitle": "TESTING"
pigallery2_testing  |   },
pigallery2_testing  |   "Media": {
pigallery2_testing  |           "Photo": {
pigallery2_testing  |                   "supportedFormats": "[\"gif\",\"jpeg\",\"jpg\",\"jpe\",\"png\",\"webp\",\"svg\",\"tif\"]"
pigallery2_testing  |           }
pigallery2_testing  |   },
pigallery2_testing  |   "Users": {
pigallery2_testing  |           "enforcedUsers": "[\"testuser\"]"
pigallery2_testing  |   },
pigallery2_testing  |   "TZ": "Europe/Amsterdam",
pigallery2_testing  |   "NODE_ENV": "debug",
pigallery2_testing  |   "NODE_VERSION": "18.12.1",
pigallery2_testing  |   "YARN_VERSION": "1.22.19",
pigallery2_testing  |   "PI_DOCKER": true,
pigallery2_testing  |   "HOME": "/root",
pigallery2_testing  |   "VIPSHOME": "/target"
pigallery2_testing  | }
pigallery2_testing  | NODE_ENV environmental variable is set to debug, forcing all logs to print
pigallery2_testing  | 1/6/2023, 10:46:49 AM[DEBUG][Worker] Worker is waiting for tasks
```

**Environment (please complete the following information):**
 - OS: Docker on Debian
 - Browser: Firefox

**Used app version**:
- docker nightly-debian-buster

**Comment by bpatrik** [comment]
I'll need to look. This is a tricky one.

Enforced users are arrays of objects that need name, password and role to
be specified.

I can't remember how the config would parse that.

I would try something like [{"name":"test", "password":"test","role":3}]

You might be able to skip setting the role but name and password you need.

-- Sorry for being brief, sent from my phone.

**Comment by mrtnbr** [comment]
Thanks. This is working:
`      - Users-enforcedUsers=[{"name":"testuser","password":"testuserpassword","role":"3"},{"name":"testadmin","password":"testadminpassword","role":"4"}]
`

**Comment by bpatrik** [comment]
You can also set this with config, run the app that will rewrite the config
by removing password and setting encrypted password.

Then You can use that encrypted password in the env variable so you do not
need to add a clear text password.

(Or you can try to manually bcrypt-t the password and use that as encrypted
password)

-- Sorry for being brief, sent from my phone.

**Comment by mrtnbr** [comment]
Thanks, good suggestion. For reference, both copying the encrypted password from config and using a tool to encrypt it work. 

`
Users-enforcedUsers=[{"name":"testuser","encryptedPassword":"$$2a$$12$$<snip>","role":"3"},{"name":"testadmin","encryptedPassword":"$$2a$$12$$<snip>","role":"4"}]
`
