### ISSUE TITLE
Possible breaking change in the config.json file sorting section

### ISSUE THREAD

**Issue by ltctceplrm** [bpatrik/pigallery2#688]
**Describe the bug**

I'm running the nightly docker container and noticed that since the last two updates the container won't start anymore, by comparing the config.json file to a blank container I spun up I noticed that the sorting section has changed to:

```json
        "//[Sorting]": [
            "If multiple preview is available sorts them by these methods and selects the first one."
        ],
        "Sorting": [
            31,
            21,
            41
        ]
```
While previously it was

```json
        "//[Sorting]": [
            "If multiple preview is available sorts them by these methods and selects the first one."
        ],
        "Sorting": [
            6,
            4
        ]

```

Once I manually the config file to reflect the new version it starts again, though I also needed to delete the database otherwise it wouldn't read the config file somehow.

**Server logs (optional)**

> TypeError: Preview.Sorting should be an Enum from values: 10,11,20,21,30,31,40,41,100,ascName,descName,ascDate,descDate,ascRating,descRating,ascPersonCount,descPersonCount,random, got: 6
>    at SubConfigClassType.__validateType (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:384:23)
>    at SubConfigClassType.__validate (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:254:29)
>    at SubConfigClassType.__validateType (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:343:51)
>    at SubConfigClassType.__validate (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:254:29)
>    at SubConfigClassType.set [as Sorting] (/app/node_modules/typeconfig/src/decorators/property/ConfigPropoerty.js:61:62)
>    at set (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:158:35)
>    at /app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:174:25
>    at Array.forEach (<anonymous>)
>    at SubConfigClassType.__loadJSONObject (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:149:39)
>    at /app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:179:41
>
>Node.js v18.17.0
>/app/node_modules/typeconfig/src/decorators/class/ConfigClass.js:151
>                            throw e;
>                            ^

**Environment (please complete the following information):**
 - OS: [debian, docker]

**Used app version**:
- docker nightly-debian-bullseye

**Comment by rhatguy** [comment]
Exact same issue upon updating my "nightly-debian-bullseye" container on my unraid instance.  Finding this, I was able to manually update the config.json file quickly and the container started successfully again.  All of my previews were gone until I ran an indexing job, but everything seems back to normal now.

**Comment by bpatrik** [comment]
Yeah the latest person based sorting messed up the config that breaks now
on startup (not yet sure if it's a bug or feature).

It's enough to delete the sorting part in you config.json

-- Sorry for being brief, sent from my phone.
