### ISSUE TITLE
GPX path not displaying since v1.9.5

### ISSUE THREAD

**Issue by lythandas** [bpatrik/pigallery2#701]
**Describe the bug**

I just updated my docker container to v1.9.5 and noticed that the GPX path on the maps are not displayed anymore

**Server logs (optional)**

No log from the server apart from this during compression : 
`8/25/2023, 2:34:14 PM[WARN_] GPXCompressionJob  Could not compress gpx at: /app/data/foobar.gpx`

**Environment (please complete the following information):**
Debian bullseye. Problem seen on Brave and Firefox

**Used app version**:
- release v1.9.5

**Comment by bpatrik** [comment]
Please try it with nightly to see if it still an issue

-- Sorry for being brief, sent from my phone.

**Comment by lythandas** [comment]
Hey bpatrik, thanks for that very quick reply. 
Unfortunately, nightly has this error on startup : 
```
TypeError: Preview.Sorting should be an Enum from values: 10,11,20,21,30,31,40,41,100,ascName,descName,ascDate,descDate,ascRating,descRating,ascPersonCount,descPersonCount,random, got: 6
    at SubConfigClassType.__validateType (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:384:23)
    at SubConfigClassType.__validate (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:254:29)
    at SubConfigClassType.__validateType (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:343:51)
    at SubConfigClassType.__validate (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:254:29)
    at SubConfigClassType.set [as Sorting] (/app/node_modules/typeconfig/src/decorators/property/ConfigPropoerty.js:61:62)
    at set (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:158:35)
    at /app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:174:25
    at Array.forEach (<anonymous>)
    at SubConfigClassType.__loadJSONObject (/app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:149:39)
    at /app/node_modules/typeconfig/src/decorators/class/base/ConfigClassBase.js:179:41

Node.js v18.17.1
/app/node_modules/typeconfig/src/decorators/class/ConfigClass.js:151
                            throw e;
                            ^
 ```

**Comment by bpatrik** [comment]
Just delete the config.json

-- Sorry for being brief, sent from my phone.

**Comment by lythandas** [comment]
Alright, now I may have some interesting piece of information .

It's still not working but now I can see this in the logs : 
```
/app/src/backend/model/fileprocessing/GPXProcessing.js:82
            const timeDelta = (Date.parse(list[i].time[0]) - Date.parse(list[i - 1].time[0])); // mill sec.
                                                      ^

TypeError: Cannot read properties of undefined (reading '0')
    at gpxEntryFilter (/app/src/backend/model/fileprocessing/GPXProcessing.js:82:55)
    at Array.filter (<anonymous>)
    at GPXProcessing.compressGPX (/app/src/backend/model/fileprocessing/GPXProcessing.js:87:51)
    at async compressGPX (/app/src/backend/middlewares/MetaFileMWs.js:24:30)

Node.js v18.13.0
```

**Comment by bpatrik** [comment]
Indeed it's more interesting:)

Can you share a broken gpx with me?

-- Sorry for being brief, sent from my phone.

**Comment by lythandas** [comment]
[islande.zip](https://github.com/bpatrik/pigallery2/files/12443434/islande.zip)

Sure, here's a gpx which is a concatenation of several paths, but it was displaying on the map before v1.9.5 (there were some issues with the display however but that's another story, I'll open another issue after we have settle this one)

**Comment by bpatrik** [comment]
The latest commit should fix it.

**Comment by lythandas** [comment]
OK ! It's working just as it used to now, but it's back with the other issue. I shall open a new issue. 
Many thanks for the fix !
