### ISSUE TITLE
Quote in search input crashes server

### ISSUE THREAD

**Issue by mcdamo** [bpatrik/pigallery2#757]
**Describe the bug**

Entering a quote `"` in search text crashes the server.

**Photo/video (optional) that causes the bug**

N/A

**Screenshots (optional)**

N/A

**Server logs (optional)**

```
undefined:1 
{"type":100,"text":"/"tokyo tower/""} 
                      ^ 
 
SyntaxError: Unexpected token t in JSON at position 22 
    at JSON.parse (<anonymous>) 
    at search (/usr/home/pigallery/pigallery2/src/backend/middlewares/GalleryMWs.js:156:28) 
    at Layer.handle [as handle_request] (/usr/home/pigallery/pigallery2/node_modules/express/lib/router/layer.js:95:5)    at next (/usr/home/pigallery/pigallery2/node_modules/express/lib/router/route.js:144:13)
    at injectGalleryVersion (/usr/home/pigallery/pigallery2/src/backend/middlewares/VersionMWs.js:14:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                        
                                                                                                                      
Node.js v18.18.2
```

**Environment (please complete the following information):**
FreeBSD 13

**Used app version**:
compiled from source 237e61c35083ddc73c2ef47ab1fb78c4e3c593ac

**Comment by bpatrik** [comment]
That looks odd. Thanks for the report. I will fix it at some point

**Comment by SteveAllen-UCOLick** [comment]
In particular this bug affects collections of family photos where a name tag on a face is something like
Robert "Bob" Ancestor
As soon as a search is done on that face the server crashes.

**Comment by svn133** [comment]
Can confirm, that this still happens with most recent version (2.0.3-edge).
Moreover, this seems to be a duplicate with #890.

Searching for special characters, or clicking on "Faces" with special characters in the person's name, lead to crash.

Happens for at least these special characters for me:
- `'`
- `?`

**Comment by bpatrik** [comment]
Last commit should fix it. Feel free to reopen if you think otherwise.
