### ISSUE TITLE
Installation Instructions Fail to Run

### ISSUE THREAD

**Issue by andrewvaughan** [bpatrik/pigallery2#78]
**Describe the bug**
Following the README's installation instructions (from source), I receive the following error at `npm start`:

```
deploy@personal-prd-www01:/var/www/gallery/pigallery2-master$ npm start

> pigallery2@1.5.9 start /var/www/gallery/pigallery2-master
> node ./backend/index

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/var/www/gallery/pigallery2-master/backend/index'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pigallery2@1.5.9 start: `node ./backend/index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pigallery2@1.5.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deploy/.npm/_logs/2019-06-25T21_19_24_245Z-debug.log
```

I attempted `sudo npm i -g typescript` and `node-ts`, but neither helped.

I even attempted to globally install `gulp` (as the `build-release` script fails without it - you might want to consider adding this to your instructions, as well).  This script fails as well:

```
deploy@personal-prd-www01:/var/www/io/thevaughans/gallery/pigallery2-master$ npm run build-release

> pigallery2@1.5.9 build-release /var/www/io/thevaughans/gallery/pigallery2-master
> gulp build-release

[21:21:47] Failed to load external module ts-node/register
[21:21:47] Error: Cannot find module 'ts-node/register' from '/var/www/io/thevaughans/gallery/pigallery2-master'
[21:21:47] Failed to load external module typescript-node/register
[21:21:47] Error: Cannot find module 'typescript-node/register' from '/var/www/io/thevaughans/gallery/pigallery2-master'
[21:21:47] Failed to load external module typescript-register
[21:21:47] Error: Cannot find module 'typescript-register' from '/var/www/io/thevaughans/gallery/pigallery2-master'
[21:21:47] Failed to load external module typescript-require
[21:21:47] Error: Cannot find module 'typescript-require' from '/var/www/io/thevaughans/gallery/pigallery2-master'
[21:21:47] Failed to load external module @babel/register
[21:21:47] Error: Cannot find module '@babel/register' from '/var/www/io/thevaughans/gallery/pigallery2-master'
[21:21:47] Local gulp not found in /var/www/io/thevaughans/gallery/pigallery2-master
[21:21:47] Try running: npm install gulp
```

Is there a dependency or step I'm missing to support TypeScript properly?  I do not normally use TS with my Node.js work.

**Enviroment (please complete the following information):**
 - OS: `Ubuntu 16.04.6 LTS`
 - Node: `v10.16.0`
 - NPM: `6.9.0`

**Used app version**: Compiled from source

**Comment by bpatrik** [comment]
Hi,

you should need to install anything globally (not even gulp). If you run the npm scripts, it will use the locally installed packages.

You first error means that the `.ts` files files are not compiled to `.js` (it cannot find `index.js`).
(And most likely you are also missing the angular build too, but you would have that error at a later point)

there are 2 way of building the app:

1) `npm install` 
 *  it installs and builds everything. It is the default way of doing it. (This is how the [heroku ](https://pigallery2.herokuapp.com/)demo is deployed)

It install all dev. dependencies too. If you would like to avoid that, you can:

2)  run `npm install` and then `npm run build-release`. 
 * You can do it on a separate computer. It will create a release folder (and probably also zips that folder too) 
      * You can observe that  in the release folder,  you have only `.js` files and the new `package.json`does not contain the dev. dependencies anymore.
 * you can copy that folder and deploy the app (on you deployed machine you should also run the `npm install` )
* This is how the [releases ](https://github.com/bpatrik/pigallery2/releases)are created. It is a more efficient way of deploying the app.

I hope it helps.

Best,
Patrik

**Comment by andrewvaughan** [comment]
Hey Patrik,

While building a more verbose response, I think I found the issue.  The `npm install` function is currently being killed internally.

Here are my exact steps, to the point of install.  You can see the not-so-helpful `killed` statement buried in the installer's status on the left at the very end:

```
deploy@personal-prd-www01:/var/www/gallery$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
deploy@personal-prd-www01:/var/www/gallery$ node -v
v10.16.0
deploy@personal-prd-www01:/var/www/gallery$ npm -v
6.9.0
deploy@personal-prd-www01:/var/www/gallery$ wget https://github.com/bpatrik/pigallery2/archive/master.zip
--2019-06-26 17:48:38--  https://github.com/bpatrik/pigallery2/archive/master.zip
Resolving github.com (github.com)... 192.30.253.112
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/bpatrik/pigallery2/zip/master [following]
--2019-06-26 17:48:38--  https://codeload.github.com/bpatrik/pigallery2/zip/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27354910 (26M) [application/zip]
Saving to: ‘master.zip’

master.zip                             100%[=========================================================================>]  26.09M   136MB/s    in 0.2s    

2019-06-26 17:48:39 (136 MB/s) - ‘master.zip’ saved [27354910/27354910]

deploy@personal-prd-www01:/var/www/gallery$ unzip master.zip
Archive:  master.zip
1bf538f818e11b50e2a08614c0fe826944c69312
   creating: pigallery2-master/
  inflating: pigallery2-master/.editorconfig  
   creating: pigallery2-master/.github/
   creating: pigallery2-master/.github/ISSUE_TEMPLATE/

### ... redacted for brevity ###

  inflating: pigallery2-master/test/e2e/tsconfig.e2e.json  
  inflating: pigallery2-master/tsconfig.json  
  inflating: pigallery2-master/tslint.json  
deploy@personal-prd-www01:/var/www/gallery$ cd pigallery2-master/
deploy@personal-prd-www01:/var/www/gallery/pigallery2-master$ npm install
Killed   ..........] / extract:gulp-json-modify: sill extract gulp-json-modify@1.0.2 extracted to /var/www/gallery/pigallery2-master/node_modules/.staging/gulp-json-modify-df7
```

Running with a higher verbosity results in the following:

```
deploy@personal-prd-www01:/var/www/gallery/pigallery2-master$ npm --verbose install
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', '--verbose', 'install' ]
npm info using npm@6.9.0
npm info using node@v10.16.0
npm verb npm-session c99e761ce609c79f
npm info lifecycle pigallery2@1.5.9~preinstall: pigallery2@1.5.9
npm timing stage:loadCurrentTree Completed in 34ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 2082ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2823ms
npm timing stage:loadIdealTree Completed in 5863ms
npm timing stage:generateActionsToTake Completed in 1346ms
npm verb correctMkdir /home/deploy/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /home/deploy/.npm/_locks/staging-1b5c9c2eeadf1728.lock for /var/www/gallery/pigallery2-master/node_modules/.staging
npm timing audit submit Completed in 1734ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 1741ms
npm timing audit body Completed in 33ms
Killed   ..........] - extract:gulp-json-modify: sill extract gulp-json-modify@1.0.2 extracted to /var/www/gallery/pigallery2-master/node_modules/.staging/gulp-json-modify-df7
```

I'm not sure if that helps.  This seems to be a custom script failing without error, maybe?  Hard to say.

**Comment by andrewvaughan** [comment]
Sorry for the double post - but I think I found the issue.  I think my VM is running out of memory, as the script failure is happening in different points.

This seems to be a poor error message on NPM's part and not any issue with your code.  Thanks for the help!  I'll go ahead and close this one.

**Comment by bpatrik** [comment]
In this case I can recommend you using option 2 and doing the `npm install` and `npm run build-release` in a separate machine. Afterwards the `npm install` with the release version should use less memory.
