### ISSUE TITLE
Periodic jobs not working/saving settings

### ISSUE THREAD

**Issue by ghost** [bpatrik/pigallery2#887]
**Describe the bug**

Periodic jobs not working when they should (everyday) or they don't even get their settings saved.

**Screenshots (optional)**

This one doesn't keep/save settings. If i select 'Monday' at 0900 and click save job, it keeps blank

GUI

![image](https://github.com/bpatrik/pigallery2/assets/144829703/b8a2034e-fe92-4811-a676-3dcc61d2f5a8)

Settings

![image](https://github.com/bpatrik/pigallery2/assets/144829703/3e706628-8719-4f11-a312-6d6e915671b7)

This one saves/keeps settings but it is not triggered everyday. It runs fine manually.

GUI

![image](https://github.com/bpatrik/pigallery2/assets/144829703/4f2526a3-8d97-4ad0-8202-9eedb42e6ad0)

Settings

![image](https://github.com/bpatrik/pigallery2/assets/144829703/5e350a8f-3734-4552-b2c1-48e56d8f93a1)

**Environment (please complete the following information):**

 - OS: dietpi
 - Browser: any

**Used app version**:

- docker-edge-bullseye 2.0.3 built at mar 12, 2024

**Comment by rhatguy** [comment]
Hit this bug also.  Running edge-debian-bullseye on Unraid.  config file is updating, but not saving correctly.  Same symptoms as @papayavice mentioned.  This is keeping indexing (and the rest of the normal jobs) from running daily.

**Comment by hobias** [comment]
I do have the same issue. The periodic scheduling is unfortunately not working. The setting is not getting applied after saving the jobs. I am currently running v2.0.3-edge built at 28.5.24.

**Comment by ltctceplrm** [comment]
I'm having the same bug and am using a temporary sort of fix by just running the tasks as an API request to the server, I used F12 in firefox to see the exact HTTP POST request and just copied it's curl command into a shell script that runs daily with crontab. It's not ideal but it does work so far.

**Comment by ltctceplrm** [comment]
Apologies for my late reply, I'll try to expand on the steps below:

1. Open your pigallery URL and go to the settings screen
2. Press F12 in firefox
3. Go to the network tab to activate it
4. Press start on the scheduled task you want to start
5. You'll see there is a POST and several GET's, you right click the POST and select copy as curl (POSIX)
![image](https://github.com/user-attachments/assets/c87fc695-9cae-4dcd-a3b3-243d9f7aa239)
6. In Linux you do `crontab -e` and add it at the bottom with a time cron schedule like [here](https://crontab.guru/)

Let me know if it worked or if you need more help

**Comment by PawelWos1987** [comment]
Indeed periodic job is not working. QNAP TS-230 - Container Station - Docker.

**Comment by bpatrik** [comment]
I made a commit that should fix the UI issue to be able to save it. 

FYI: The workaround for this issue would have been is to just manually update the config.json.

Note: I haven't tested if the job would indeed run periodically, only that the config change can be saved. Let me know if the there is also an issue with running.

Closing this bug as fixed, feel free to reopen if you think otherwise.

**Comment by ltctceplrm** [comment]
Is this commit in the latest edge build? Because if so the time to start the job is still not being saved.

In fact if you try to add a timestamp to an existing job then you cannot press save at all since it doesn't detect any changes, if you change something else of that job then you can save but it still just skips the time and doesn't save that.

Edit: Completely re-creating the jobs saves to config.json but if you reload the page then the time info is not visible on the website (yes in the config though), I will test if it auto sends the mail tomorrow.

**Comment by bpatrik** [comment]
That sounds to me that you are not running the latest edge. I could not reproduce it on https://pigallery2.onrender.com/admin. Can you try doing so?

Note: one of the alpine arm build was dropped so it wont receive updates for the edge build. See running version on the admin tab, hovering over the version name for more details.

**Comment by ltctceplrm** [comment]
> That sounds to me that you are not running the latest edge.

Well this is embarassing, apparently I was still on `bpatrik/pigallery2:edge-debian-buster` which no longer exists and the last build was from last year, I don't know how I never noticed that the tag was invalid.

I'm on `edge-debian-bookworm` now and I can confirm that the latest edge completely fixes the problem.

**Comment by bpatrik** [comment]
Yeah I just found today that there is still the legacy `edge-debian-buster` tag. Just removed to avoid confusions. 

Great I will close this then.

**Comment by ltctceplrm** [comment]
Don't reopen the ticket just yet but I think it might still not be fixed, I didn't notice immediately because I still had the daily crontab to manually run the top pick sending but once I remembered to turn that off I stopped getting the daily email, the logs give this error:

```
11/1/2025, 5:00:00 AM[INFO_][JOB] Running job : Indexing
11/1/2025, 5:00:27 AM[INFO_][JOB] Job finished: Indexing
11/1/2025, 5:00:27 AM[INFO_][JOB] Running job : Album Cover Filling
/app/src/backend/model/jobs/JobManager.js:64
throw new Error('Can't start this job while another is running');
^

Error: Can't start this job while another is running
at JobManager.run (/app/src/backend/model/jobs/JobManager.js:64:19)
at Timeout._onTimeout (/app/src/backend/model/jobs/JobManager.js:118:28)
at listOnTimeout (node:internal/timers:588:17)
at process.processTimers (node:internal/timers:523:7)

Node.js v22.20.0
11/1/2025, 8:50:02 AM[INFO_][server] running diagnostics...
11/1/2025, 8:50:02 AM[INFO_][JobManager] Running job schedules

11/1/2025, 8:50:02 AM[INFO_][server] Listening on port 80
```

The top pick sending was scheduled for 8:50 so I assumed something goes wrong each time just before it sends, I'd already enabled parallel runs but it didn't help, so I tested running top pick sending later in the day to see if it helps but it just gives the same error with different times:

```
11/3/2025, 4:00:00 AM[INFO_][JOB] Running job : Indexing
11/3/2025, 4:00:11 AM[INFO_][JOB] Job finished: Indexing
11/3/2025, 4:00:11 AM[INFO_][JOB] Running job : Album Cover Filling
/app/src/backend/model/jobs/JobManager.js:64
            throw new Error('Can\'t start this job while another is running');
                  ^

Error: Can't start this job while another is running
    at JobManager.run (/app/src/backend/model/jobs/JobManager.js:64:19)
    at Timeout._onTimeout (/app/src/backend/model/jobs/JobManager.js:118:28)
    at listOnTimeout (node:internal/timers:588:17)
    at process.processTimers (node:internal/timers:523:7)

Node.js v22.20.0
11/3/2025, 9:30:02 AM[INFO_][server] running diagnostics...
11/3/2025, 9:30:03 AM[INFO_][JobManager] Running job schedules
11/3/2025, 9:30:03 AM[INFO_][server] Listening on port 80
```

My next troubleshooting step is just disabling album cover filing to see if that fixes it because then this is just a totally different problem

**Comment by bpatrik** [comment]
Lets move this to a spearate issue for better tracking. the original issue (not being able to change the config) was resolved

**Comment by bpatrik** [comment]
@ltctceplrm see #1063
