### ISSUE TITLE
Unable to Index Symlinked Directory

### ISSUE THREAD

**Issue by ameer1234567890** [bpatrik/pigallery2#905]
I have a folder of images which is symlinked to PiGallery2's images folder. Unfortunately, PiGallery2 is unable to index the folder throwing the below error.

```
5/13/2024, 6:13:24 PM[INFO_][server] running diagnostics...
5/13/2024, 6:13:24 PM[INFO_][JobManager] Running job schedules
5/13/2024, 6:13:24 PM[INFO_][server] Listening on port 80
5/13/2024, 6:13:42 PM[INFO_][JOB] Running job : Indexing
[Error: ENOENT: no such file or directory, stat '/app/data/images/2016/Futsal 2016'] {

  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/app/data/images/2016/Futsal 2016'
}
5/13/2024, 6:13:42 PM[WARN_][IndexingJob] Skipping. Indexing failed for: /
[Error: ENOENT: no such file or directory, stat '/app/data/images/2016/Futsal 2016'] {

  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/app/data/images/2016/Futsal 2016'
}
5/13/2024, 6:13:42 PM[ERROR][JOB] Job failed with:
5/13/2024, 6:13:42 PM[ERROR][JOB] TypeError: Cannot read properties of null (reading 'directories')
    at IndexingJob.step (/app/src/backend/model/jobs/jobs/IndexingJob.js:90:36)
    at async /app/src/backend/model/jobs/jobs/Job.js:101:22
```

**Comment by bpatrik** [comment]
symlink does not work within docker (its a docker limitation)

**Comment by ameer1234567890** [comment]
I found the workaround was to also mount the directory being symlinked to, as a volume. It works now.
