### ISSUE TITLE
Indexing doesn't finish

### ISSUE THREAD

**Issue by palitu** [bpatrik/pigallery2#93]
**Describe the bug**
Indexing my files does not complete.  When indexing, it stops around the 4k files mark, when in reality there is approximately 50k photos. 

re-indexing does not solve the problem.

**Photo/video (optional) that causes the bug**
If error is in connection with a particular photo/video, It would help a lot with the debugging if you can attach that file too.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Kubuntu 18.04
 - Browser: Opera
 

**Used app version**:
- docker-nightly

I am running the latest docker container, with MySQL backend.  The photo structure is is volume mounted directly into the container in the default location.

I have logging set to 5 & 3 for app and MySQL respecitvely and the last photo that is indexed is shown below.  After that file, there is no further logging output to the console.  

```
pigallery       | query: ROLLBACK
pigallery       | { QueryFailedError: ER_DUP_ENTRY: Duplicate entry 'IMG_0995.jpg-76' for key 'IDX_332f316a46fcb158ac71210109'
pigallery       |     at new QueryFailedError (/pigallery2-release/node_modules/typeorm/error/QueryFailedError.js:11:28)
pigallery       |     at Query.<anonymous> (/pigallery2-release/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:167:45)
pigallery       |     at Query.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:502:10)
pigallery       |     at Query._callback (/pigallery2-release/node_modules/mysql/lib/Connection.js:468:16)
pigallery       |     at Query.Sequence.end (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
pigallery       |     at Query.ErrorPacket (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
pigallery       |     at Protocol._parsePacket (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:278:23)
pigallery       |     at Parser.write (/pigallery2-release/node_modules/mysql/lib/protocol/Parser.js:76:12)
pigallery       |     at Protocol.write (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:38:16)
pigallery       |     at Socket.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:91:28)
pigallery       |   message:
pigallery       |    'ER_DUP_ENTRY: Duplicate entry \'IMG_0995.jpg-76\' for key \'IDX_332f316a46fcb158ac71210109\'',
pigallery       |   code: 'ER_DUP_ENTRY',
pigallery       |   errno: 1062,
pigallery       |   sqlMessage:
pigallery       |    'Duplicate entry \'IMG_0995.jpg-76\' for key \'IDX_332f316a46fcb158ac71210109\'',
pigallery       |   sqlState: '23000',
pigallery       |   index: 0,
pigallery       |   sql:
pigallery       |    'INSERT INTO `media_entity`(`id`, `name`, `type`, `directoryId`, `metadataCaption`, `metadataCreationdate`, `metadataFilesize`, `metadataKeywords`, `metadataOrientation`, `metadataBitrate`, `metadataDuration`, `metadataSizeWidth`, `metadataSizeHeight`, `metadataCameraDataIso`, `metadataCameraDataModel`, `metadataCameraDataMake`, `metadataCameraDataFstop`, `metadataCameraDataExposure`, `metadataCameraDataFocallength`, `metadataCameraDataLens`, `metadataPositionDataCountry`, `metadataPositionDataState`, `metadataPositionDataCity`, `metadataPositionDataGPSDataLatitude`, `metadataPositionDataGPSDataLongitude`, `metadataPositionDataGPSDataAltitude`) VALUES (DEFAULT, \'IMG_0995.jpg\', \'PhotoEntity\', 76, DEFAULT, 1323184378000, 2198584, \'\', 1, DEFAULT, DEFAULT, 2592, 1936, 80, \'iPhone 4\', \'Apple\', 2.8, 0.058823529411764705, 3.85, DEFAULT, DEFAULT, DEFAULT, DEFAULT, -32.04533333333333, 115.81633333333333, 31.19884726224784)',
pigallery       |   name: 'QueryFailedError',
pigallery       |   query:
pigallery       |    'INSERT INTO `media_entity`(`id`, `name`, `type`, `directoryId`, `metadataCaption`, `metadataCreationdate`, `metadataFilesize`, `metadataKeywords`, `metadataOrientation`, `metadataBitrate`, `metadataDuration`, `metadataSizeWidth`, `metadataSizeHeight`, `metadataCameraDataIso`, `metadataCameraDataModel`, `metadataCameraDataMake`, `metadataCameraDataFstop`, `metadataCameraDataExposure`, `metadataCameraDataFocallength`, `metadataCameraDataLens`, `metadataPositionDataCountry`, `metadataPositionDataState`, `metadataPositionDataCity`, `metadataPositionDataGPSDataLatitude`, `metadataPositionDataGPSDataLongitude`, `metadataPositionDataGPSDataAltitude`) VALUES (DEFAULT, ?, ?, ?, DEFAULT, ?, ?, ?, ?, DEFAULT, DEFAULT, ?, ?, ?, ?, ?, ?, ?, ?, DEFAULT, DEFAULT, DEFAULT, DEFAULT, ?, ?, ?)',
pigallery       |   parameters:
pigallery       |    [ 'IMG_0995.jpg',
pigallery       |      'PhotoEntity',
pigallery       |      76,
pigallery       |      1323184378000,
pigallery       |      2198584,
pigallery       |      '',
pigallery       |      1,
pigallery       |      2592,
pigallery       |      1936,
pigallery       |      80,
pigallery       |      'iPhone 4',
pigallery       |      'Apple',
pigallery       |      2.8,
pigallery       |      0.058823529411764705,
pigallery       |      3.85,
pigallery       |      -32.04533333333333,
pigallery       |      115.81633333333333,
pigallery       |      31.19884726224784 ] }
```

**Comment by bpatrik** [comment]
Hi,

Did this work before? (I made some changes that should not effect this, but might happen).
Also is it possible that you somehow have (?) two photos with the same name in one directory?

Patrik

**Comment by palitu** [comment]
Yeah - heaps with the same name, just different case.

I haven't used for 6 months or so, so I'm not sure. I was looking for an
obvious reason for it stopping, but the logs are not indicating anything.

I might try add some logging to see each file that is being checked.

**Comment by bpatrik** [comment]
Hi,

Can you make sure that your nightly is up-to date?
I have fixed the case sensitive issue a while ago.

Patrik

**Comment by palitu** [comment]
Hahah, yeah I know, you fixed it for me! I don't think it is the file name,
as you had fixed that, hence why it says that it is skipping the duplicate.

But not sure how to see where it gets up to before stopping

**Comment by bpatrik** [comment]
Hi,

You can set the logging at `config.json` to 
```json
"log": {
            "level": 5,
            "sqlLevel": 3
        }
```

From your log it looks like that you have the exactly same file name (same casing) in the same folder.
My educated guess that you might have something like this:
```
folder1
   IMG.jpg
Folder1
   IMG.jpg
```

So I made a fix and test for folder names and path to be case sensitive. You can try it with the latest nightly.

**Comment by palitu** [comment]
Yep - that is a good point.

I have:
```
- 2018
  |- 01 Jan
  |- 02 Feb
  |- ...
  |- 12 Dec
- 2019
  |- 01 Jan
  |- 02 Feb
  |- ...
  |- 12 Dec
```
So that sounds like a perfect guess.  I'm trying now

**Comment by palitu** [comment]
Yep - here it is:

```
pigallery       | error: { Error: ER_DUP_ENTRY: Duplicate entry '12 Dec-2011/' for key 'IDX_05d748647d27bf887ef0826de7'
pigallery       |     at Query.Sequence._packetToError (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
pigallery       |     at Query.ErrorPacket (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
pigallery       |     at Protocol._parsePacket (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:278:23)
pigallery       |     at Parser.write (/pigallery2-release/node_modules/mysql/lib/protocol/Parser.js:76:12)
pigallery       |     at Protocol.write (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:38:16)
pigallery       |     at Socket.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:91:28)
pigallery       |     at Socket.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:502:10)
pigallery       |     at Socket.emit (events.js:198:13)
pigallery       |     at addChunk (_stream_readable.js:288:12)
pigallery       |     at readableAddChunk (_stream_readable.js:269:11)
pigallery       |     --------------------
pigallery       |     at Protocol._enqueue (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:144:48)
pigallery       |     at PoolConnection.query (/pigallery2-release/node_modules/mysql/lib/Connection.js:200:25)
pigallery       |     at MysqlQueryRunner.<anonymous> (/pigallery2-release/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:158:44)
pigallery       |     at step (/pigallery2-release/node_modules/tslib/tslib.js:136:27)
pigallery       |     at Object.next (/pigallery2-release/node_modules/tslib/tslib.js:117:57)
pigallery       |     at fulfilled (/pigallery2-release/node_modules/tslib/tslib.js:107:62)
pigallery       |     at process._tickCallback (internal/process/next_tick.js:68:7)
pigallery       |   code: 'ER_DUP_ENTRY',
pigallery       |   errno: 1062,
pigallery       |   sqlMessage:
pigallery       |    'Duplicate entry \'12 Dec-2011/\' for key \'IDX_05d748647d27bf887ef0826de7\'',
pigallery       |   sqlState: '23000',
pigallery       |   index: 0,
pigallery       |   sql:
pigallery       |    'INSERT INTO `directory_entity`(`id`, `name`, `path`, `lastModified`, `lastScanned`, `mediaCount`, `parentId`) VALUES (NULL, \'12 Dec\', \'2011/\', 1550273187687, NULL, 3, 194)' }
pigallery       | { QueryFailedError: ER_DUP_ENTRY: Duplicate entry '12 Dec-2011/' for key 'IDX_05d748647d27bf887ef0826de7'
pigallery       |     at new QueryFailedError (/pigallery2-release/node_modules/typeorm/error/QueryFailedError.js:11:28)
pigallery       |     at Query.<anonymous> (/pigallery2-release/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:167:45)
pigallery       |     at Query.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:502:10)
pigallery       |     at Query._callback (/pigallery2-release/node_modules/mysql/lib/Connection.js:468:16)
pigallery       |     at Query.Sequence.end (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
pigallery       |     at Query.ErrorPacket (/pigallery2-release/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
pigallery       |     at Protocol._parsePacket (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:278:23)
pigallery       |     at Parser.write (/pigallery2-release/node_modules/mysql/lib/protocol/Parser.js:76:12)
pigallery       |     at Protocol.write (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:38:16)
pigallery       |     at Socket.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:91:28)
pigallery       |   message:
pigallery       |    'ER_DUP_ENTRY: Duplicate entry \'12 Dec-2011/\' for key \'IDX_05d748647d27bf887ef0826de7\'',
pigallery       |   code: 'ER_DUP_ENTRY',
pigallery       |   errno: 1062,
pigallery       |   sqlMessage:
pigallery       |    'Duplicate entry \'12 Dec-2011/\' for key \'IDX_05d748647d27bf887ef0826de7\'',
pigallery       |   sqlState: '23000',
pigallery       |   index: 0,
pigallery       |   sql:
pigallery       |    'INSERT INTO `directory_entity`(`id`, `name`, `path`, `lastModified`, `lastScanned`, `mediaCount`, `parentId`) VALUES (NULL, \'12 Dec\', \'2011/\', 1550273187687, NULL, 3, 194)',
pigallery       |   name: 'QueryFailedError',
pigallery       |   query:
pigallery       |    'INSERT INTO `directory_entity`(`id`, `name`, `path`, `lastModified`, `lastScanned`, `mediaCount`, `parentId`) VALUES (?, ?, ?, ?, ?, ?, ?)',
pigallery       |   parameters: [ null, '12 Dec', '2011/', 1550273187687, null, 3, 194 ] }
```

**Comment by bpatrik** [comment]
Hm. This one should not actually happen. 
Can you try 2 things:

* Making sure that you have the latest (the admin page now shows the version next to the 'mode selection button)
 * reset your database (to make sure: manually deleting all tables) then rerunning the indexing.

Thanks,
P

**Comment by palitu** [comment]
Ok, i did a full removal of the DB & Pig2 images, volumes and networks.  Ran through and they are all good now!

That said, i still cannot see the version number in the admin section

cheers

**Comment by bpatrik** [comment]
Hi,

thanks. Probably there was some inconsistency with the DB. 
Also, I suspect for some reason docker does not download the latest image for you. You should see the version here (you can check it on the[ heroku demo](https://pigallery2.herokuapp.com/)):

![ver](https://user-images.githubusercontent.com/7512182/61618572-6789af00-ac6d-11e9-947c-66544598c010.jpg)
As an alternative, you can try using `1.7.0-stretch` instead of `nightly-stretch` image.

**Comment by palitu** [comment]
I don't think it would be the dB, I deleted and restarted it quite often.

And forced redownloads by deleting the images.

Anyway, all up and running with 65k Images

Thanks - closed

**Comment by bpatrik** [comment]
Okay. Let me know if you have this issue again.
P

**Comment by bpatrik** [comment]
There was indeed a bug that causes very similar Foreign key error that you also reported:
If you indexed a sub folder before its parent folder. 
Namely if you reset the DB then open the <mygallery url>/gallery/subdir first, then <mygallery url>/gallery/ you get a foreign key error.
The last commit should fix it.

Also the docker nightly should also work now. (It had caching enabled that prevented using the latest commit for build)

**Comment by palitu** [comment]
Cheers I'll try it out again.

And I'll pull a new container
