### ISSUE TITLE
Install failed: sqlite3@4.0.4

### ISSUE THREAD

**Issue by beli3ver** [bpatrik/pigallery2#94]
Hello,

I tried to install the software, and get these errors:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dietpi/.npm/_logs/2019-07-20T18_37_32_040Z-debug.log
```
Part of the log:

> 4285 verbose optional SKIPPING OPTIONAL DEPENDENCY:
> 4285 verbose optional Failed at the bcrypt@3.0.2 install script.
> 4285 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
> 4286 warn optional SKIPPING OPTIONAL DEPENDENCY: sharp@0.21.1 (node_modules/sharp):
> 4287 warn optional SKIPPING OPTIONAL DEPENDENCY: sharp@0.21.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
> 4287 warn optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 4288 verbose optional SKIPPING OPTIONAL DEPENDENCY:
> 4288 verbose optional Failed at the sharp@0.21.1 install script.
> 4288 verbose optional SKIPPING OPTIONAL DEPENDENCY: This is probably not a problem with npm. There is likely additional logging output above.
> 4289 verbose stack Error: sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
> 4289 verbose stack Exit status 1
> 4289 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
> 4289 verbose stack     at EventEmitter.emit (events.js:198:13)
> 4289 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 4289 verbose stack     at ChildProcess.emit (events.js:198:13)
> 4289 verbose stack     at maybeClose (internal/child_process.js:982:16)
> 4289 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> 4290 verbose pkgid sqlite3@4.0.4
> 4291 verbose cwd /home/dietpi/pigallery2
> 4292 verbose Linux 4.19.57-v7+
> 4293 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
> 4294 verbose node v10.16.0
> 4295 verbose npm  v6.9.0
> 4296 error code ELIFECYCLE
> 4297 error errno 1
> 4298 error sqlite3@4.0.4 install: `node-pre-gyp install --fallback-to-build`
> 4298 error Exit status 1
> 4299 error Failed at the sqlite3@4.0.4 install script.
> 4299 error This is probably not a problem with npm. There is likely additional logging output above.
> 4300 verbose exit [ 1, true ]

I follow there steps, all as normal user
```bash
cd ~
wget https://github.com/bpatrik/pigallery2/releases/download/1.5.6/pigallery2.zip
unzip pigallery2.zip -d pigallery2
cd pigallery2
npm install
```
System info:

```bash
root@DietPi:/# uname -a
Linux DietPi 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux
root@DietPi:/# nodejs --version
v10.16.0
root@DietPi:/# dpkg -l | grep sqlite
ii  libsqlite3-0:armhf         3.16.2-5+deb9u1              armhf        SQLite 3 shared library
ii  sqlite3                    3.16.2-5+deb9u1              armhf        Command line interface for SQLite 3
root@DietPi:/# 
```

**Comment by bpatrik** [comment]
Hi,

Its hard to tell from this.
```
4298 error sqlite3@4.0.4 install: node-pre-gyp install --fallback-to-build
4298 error Exit status 1
```

From this it looks like that it tries to install and build sqlite from source, but it could not. My guess would be that you are [missing](https://github.com/bpatrik/pigallery2#node-install-error) something like `apt-get install build-essential  libkrb5-dev gcc g++`.

Patrik

**Comment by beli3ver** [comment]
I have installed these packages no changes still the same error.
I tried it as root, too. Still the same.

**Comment by bpatrik** [comment]
Sorry, but I don't have any experience with DietPi. :/
What happens when you just install the sqlite npm module globally? `npm i -g sqlite3` ? (it will install the latest sqlite mode, maybe that works)
Also installing sqlite or the others via `apt-get install` is necessary and also not enough as the app is looking for the `sqlite3` npm package.

**Comment by captinsteven** [comment]
Hi beli3ver,
I encountered same error as you at first. But after I found below article and followed its instruction to modify permissions, I got it work.
https://github.com/bpatrik/pigallery2/issues/98

**Comment by bpatrik** [comment]
I'm closing this due to inactivity
