### ISSUE TITLE
Error: Packets out of order. Got: 1 Expected: 0 (MySQL/MariDB)

### ISSUE THREAD

**Issue by modzilla99** [bpatrik/pigallery2#96]
When trying to connect to my mariaDB container, it will always fail with an error! I'm using the latest 1.7.0 image and mariaDB:latest! I hope this is not some stuff on my end :/

The warning in the mariaDB container log:

> [Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: '172.20.0.6' (This connection closed normally without authentication)

PiGallery's logs:

> pygallery       | 8/13/2019, 6:38:11 PM[INFO] [server] Listening on port 80
> pygallery       | 8/13/2019, 6:39:31 PM[WARN] Handled error:
> pygallery       | ErrorDTO {
> pygallery       |   code: 13,
> pygallery       |   message:
> pygallery       |    'Error while saving database settings: Error: Packets out of order. Got: 1 Expected: 0',
> pygallery       |   details:
> pygallery       |    { Error: Packets out of order. Got: 1 Expected: 0
> pygallery       |        at Parser._tryReadPacketHeader (/pigallery2-release/node_modules/mysql/lib/protocol/Parser.js:470:15)
> pygallery       |        at Parser.write (/pigallery2-release/node_modules/mysql/lib/protocol/Parser.js:33:29)
> pygallery       |        at Protocol.write (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:38:16)
> pygallery       |        at Socket.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:91:28)
> pygallery       |        at Socket.<anonymous> (/pigallery2-release/node_modules/mysql/lib/Connection.js:525:10)
> pygallery       |        at Socket.emit (events.js:198:13)
> pygallery       |        at addChunk (_stream_readable.js:288:12)
> pygallery       |        at readableAddChunk (_stream_readable.js:269:11)
> pygallery       |        at Socket.Readable.push (_stream_readable.js:224:10)
> pygallery       |        at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
> pygallery       |        --------------------
> pygallery       |        at Protocol._enqueue (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:144:48)
> pygallery       |        at Protocol.handshake (/pigallery2-release/node_modules/mysql/lib/protocol/Protocol.js:51:23)
> pygallery       |        at PoolConnection.connect (/pigallery2-release/node_modules/mysql/lib/Connection.js:119:18)
> pygallery       |        at Pool.getConnection (/pigallery2-release/node_modules/mysql/lib/Pool.js:48:16)
> pygallery       |        at /pigallery2-release/node_modules/typeorm/driver/mysql/MysqlDriver.js:764:18
> pygallery       |        at new Promise (<anonymous>)
> pygallery       |        at MysqlDriver.createPool (/pigallery2-release/node_modules/typeorm/driver/mysql/MysqlDriver.js:761:16)
> pygallery       |        at MysqlDriver.<anonymous> (/pigallery2-release/node_modules/typeorm/driver/mysql/MysqlDriver.js:274:51)
> pygallery       |        at step (/pigallery2-release/node_modules/tslib/tslib.js:136:27)
> pygallery       |        at Object.next (/pigallery2-release/node_modules/tslib/tslib.js:117:57) code: 'PROTOCOL_PACKETS_OUT_OF_ORDER', fatal: true } }

**Comment by bpatrik** [comment]
Hi,

You get this error while he app tries to connect to your db and it seems that it cannot.
At the first look it seems that the error is some configuration error.
Can you please check if your are trying to connect to an existing dabatase within your mariadb? (the app can only create the tables within the db, not the db itself)
Also can maybe check if you can connect to the db from an other application?

Best,
Patrik

**Comment by bpatrik** [comment]
closing this due to inactivity
