### ISSUE TITLE
Settings error: Error: Unknown Job :Thumbnail Generation

### ISSUE THREAD

**Issue by kerryland** [bpatrik/pigallery2#961]
I have just updated to 2.0.3-edge, built October 27th, and the /admin page is providing a "Server Notification":
```
(1) Jobs error. Resetting to default for now to let the app start up. Please adjust the config properly.
"Error: Unknown Job :Thumbnail Generation"
```

Attempts to change "Exclude folder list" are rejected with "Error: Settings error: Error: Unknown Job :Thumbnail Generation" when I click save.

**Server logs (optional)**
```
12/19/2024, 1:20:42 AM[INFO_][JOB] Running job : Indexing
12/19/2024, 1:21:02 AM[INFO_][JOB] Job finished: Indexing
12/19/2024, 1:21:02 AM[INFO_][JOB] Running job : Album Cover Filling
12/19/2024, 1:24:51 AM[INFO_][JOB] Job finished: Album Cover Filling
12/19/2024, 1:24:51 AM[INFO_][JOB] Running job : Photo Converting
12/19/2024, 1:25:09 AM[ERROR] ErrorDTO {
  code: 60,
  message: 'Settings error: Error: Unknown Job :Thumbnail Generation',
  details: Error: Unknown Job :Thumbnail Generation
      at ConfigDiagnostics.testJobsConfig (/app/src/backend/model/diagnostics/ConfigDiagnostics.js:60:23)
      at ConfigDiagnostics.testConfig (/app/src/backend/model/diagnostics/ConfigDiagnostics.js:272:33)
      at async updateSettings (/app/src/backend/middlewares/admin/SettingsMWs.js:41:13),
  request: { method: '', url: '' }
}
```
and some more -- perhaps unrelated.
```
(process:1): GLib-GObject-WARNING **: 01:30:31.197: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'

(process:1): GLib-GObject-WARNING **: 01:30:31.197: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'
[Error: extract_area: parameter width not set
extract_area: parameter height not set
]
12/19/2024, 1:30:31 AM[ERROR] ErrorDTO {
  code: 32,
  message: 'Error during generating face thumbnail: Themis',
  details: 'Error: extract_area: parameter width not set\n' +
    'extract_area: parameter height not set\n',
  request: { method: '', url: '' }
}

(process:1): GLib-GObject-WARNING **: 01:30:31.222: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'

(process:1): GLib-GObject-WARNING **: 01:30:31.222: value "0" of type 'gint' is invalid or out of range for property 'height' of type 'gint'
[Error: extract_area: parameter width not set
extract_area: parameter height not set
]
12/19/2024, 1:30:31 AM[ERROR] ErrorDTO {
  code: 32,
  message: 'Error during generating face thumbnail: Vivian Greece',
  details: 'Error: extract_area: parameter width not set\n' +
    'extract_area: parameter height not set\n',
  request: { method: '', url: '' }
}
12/19/2024, 1:30:47 AM[ERROR] ErrorDTO {
  code: 60,
  message: 'Settings error: Error: Unknown Job :Thumbnail Generation',
  details: Error: Unknown Job :Thumbnail Generation
      at ConfigDiagnostics.testJobsConfig (/app/src/backend/model/diagnostics/ConfigDiagnostics.js:60:23)
      at ConfigDiagnostics.testConfig (/app/src/backend/model/diagnostics/ConfigDiagnostics.js:272:33)
      at async updateSettings (/app/src/backend/middlewares/admin/SettingsMWs.js:41:13),
  request: { method: '', url: '' }
}
```

**Environment (please complete the following information):**
 - OS: server runs on pi4, browser on windows 10
 - Browser: chrome

**Used app version**:
- docker-edge (alpine)

**Comment by kerryland** [comment]
...so I blew the database away and started again. Problem solved. I notice that I no longer have a "Thumbnail Generation" job listed, so I guess that explains the error message nicely :-)

**Comment by GWONG3** [comment]
> ...so I blew the database away and started again. Problem solved. I notice that I no longer have a "Thumbnail Generation" job listed, so I guess that explains the error message nicely :-)

How did you blew the database?  I tried to perform a gallery reset and run reindex and the promise still exists....

**Comment by kerryland** [comment]
I think I just deleted "sqlite.db" from the directory linked to "app/data/db". I probably deleted "jobs.db" too, but I'm not sure.

**Comment by edwin-nz** [comment]
The only way to get rid of that message for me when I upgraded is to blow away my old config.json and let the new version write a new one. Then manually put back in all my config using the new UI in the new version.

**Comment by Marxsal** [comment]
It looks to me like "Photo Converting " took over the job of Thumbnail Generation.

If you go into admin settings and delete "Thumbnail Generation" and then set "Photo Converting" to come *after* "Album Cover Filling", save, and restart your pigallery app, the message goes away.

**Comment by bpatrik** [comment]
the comments above are correct.

The job name changed that broke the config. simplest fix is to delete to config file. 
A more conservative fix to delete that part of the json in the config file. THe config json can be sparse, the app will fill in with the default value. But it must be a correct json otherwise the app wont start.
